$ErrorActionPreference = "Stop"
$targetDir = "C:\Users\LAB\Desktop\Hausa Tech\TechHausa\TechHausa\app\src\main\assets\courses"
function Add-Diag {
    param($file, $id, $diag)
    $raw = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8)
    $search = '"id": "' + $id + '"'
    $idPos = $raw.IndexOf($search)
    if ($idPos -lt 0) { Write-Output ("SKIP " + $id); return }
    $quizPos = $raw.IndexOf('"quiz":', $idPos)
    if ($quizPos -lt 0) { Write-Output ("NOQUIZ " + $id); return }
    $raw = $raw.Insert($quizPos, '            "supplementaryDiagrams": ' + $diag + ",`n")
    [System.IO.File]::WriteAllText($file, $raw, [System.Text.Encoding]::UTF8)
    Write-Output ("OK " + $id)
}
$f = "$targetDir\ai.json"
Add-Diag $f 'ai-b1' '[{"type":"flow","title":"Yadda AI Ke Aiki","items":["Tattara Bayanai","Koyo Daga Misalai","Gano Siffofi","Bayar Da Amsa"],"caption":"AI tana koyo daga bayanai masu yawa"},{"type":"compare","title":"Narrow AI Da General AI","leftTitle":"Narrow AI","leftItems":["Aiki Daya Kacal","Yana Wanzuwa A Yau","Misali Siri Da Alexa"],"rightTitle":"General AI","rightItems":["Kowane Fanni Kamar Mutum","Har Yanzu Raayi Ne","Ba A Samu Ba Tukuna"]},{"type":"hub","title":"AI A Rayuwar Yau","center":"AI","satellites":["Google Maps","Netflix","Face Unlock","Siri","ChatGPT"]},{"type":"stack","title":"Matakan AI","items":["Aikace Aikace","Frameworks","Machine Learning","Bayanai"]}]'
Add-Diag $f 'ai-b2' '[{"type":"flow","title":"Yadda Koyo Ke Faruwa","items":["Shigar Da Bayanai","Nuna Misalai Da Amsoshi","Model Ya Gano Siffofi","Gwada Da Sabbin Bayanai"],"caption":"Koyo yana bukatar bayanai masu yawa"},{"type":"compare","title":"Bayanai Masu Kyau Da Mara Kyau","leftTitle":"Masu Kyau","leftItems":["Masu Yawa","Daidai","Akan Juna"],"rightTitle":"Mara Kyau","rightItems":["Kadan","Kuskure","Bata Da Daidaito"]},{"type":"hub","title":"Abubuwan Da AI Ke Bukata","center":"Koyo","satellites":["Bayanai","Misalai","Lissafi","Gwaji"]},{"type":"stack","title":"Matakan Gina Model","items":["Tantancewa","Horaswa","Shirya Bayanai","Tattara Bayanai"]}]'
Add-Diag $f 'ai-b3' '[{"type":"flow","title":"Misalan AI A Yau","items":["Wayar Hannu","Gida","Aiki","Nishadi"],"caption":"AI tana ko ina a rayuwarmu"},{"type":"compare","title":"Assistance Da Automation","leftTitle":"Assistance","leftItems":["Taimako","Mutum Ya Yanke Shawara","Misali Siri"],"rightTitle":"Automation","rightItems":["Aiki Da Kanta","Ba Mutum","Misali Motar Da Ke Tafiya Da Kanta"]},{"type":"hub","title":"AI A Naurori","center":"AI","satellites":["Wayar Hannu","Kwamfuta","Mota","Gida Mai Wayo"]},{"type":"stack","title":"Aikace Aikacen AI","items":["ChatGPT","Google Translate","Face Unlock","Netflix"]}]'
Add-Diag $f 'ai-b4' '[{"type":"flow","title":"Yadda Chatbot Ke Aiki","items":["Karbar Tambayarka","Fahimtar Maana","Neman Amsa","Bayar Da Amsa"],"caption":"Chatbot yana amsa tambayoyi cikin sauri"},{"type":"compare","title":"ChatGPT Da Gemini","leftTitle":"ChatGPT","leftItems":["OpenAI Ta Samar","Mafi Shahara","Yana Da API"],"rightTitle":"Gemini","rightItems":["Google Ta Samar","Yana Hadawa Da Google","Sabon Fasali"]},{"type":"hub","title":"Chatbots Shahararru","center":"Chatbots","satellites":["ChatGPT","Claude","Gemini","Copilot"]},{"type":"stack","title":"Matakan Chatbot","items":["User Interface","NLP Engine","Language Model","Training Data"]}]'
Add-Diag $f 'ai-b5' '[{"type":"flow","title":"Rubuta Umarni Mai Kyau","items":["Fadi Abin Da Kake So","Bada Bayani","Bada Misali","Gyara Amsar"],"caption":"Umarni mai kyau yana bada amsa mai kyau"},{"type":"compare","title":"Umarni Gajere Da Cikakke","leftTitle":"Gajere","leftItems":["Gajere","Mara Bayani","Amsa Mara Daidaito"],"rightTitle":"Cikakke","rightItems":["Tsayi","Mai Bayani","Amsa Mai Daidaito"]},{"type":"hub","title":"Abubuwan Umarni","center":"Prompt","satellites":["Manufa","Bayani","Misali","Tsari"]},{"type":"stack","title":"Matakan Prompting","items":["Gwadawa","Gyara Amsa","Bada Misali","Rubuta Manufa"]}]'
Add-Diag $f 'ai-b6' '[{"type":"flow","title":"Matsalolin AI","items":["Rashin Daidaito","Son Zuciya","Matsalar Sirri","Dogaro Da Yawa"],"caption":"AI tana da iyakoki da hatsarori"},{"type":"compare","title":"Abin Dogara Da Maras Dogara","leftTitle":"Abin Dogara","leftItems":["Duba Amsar","Yi Amfani Da Hikima","Kada A Yarda Da Kome"],"rightTitle":"Maras Dogara","rightItems":["Yarda Da Kome","Babu Dubawa","Dogaro Da Yawa"]},{"type":"hub","title":"Iyakokin AI","center":"Iyaka","satellites":["Hallucination","Bias","Privacy","Deepfakes"]},{"type":"stack","title":"Amfani Mai Hankali","items":["Duba Gaskiya","Kare Sirri","Guji Son Zuciya","Ci Gaba Da Koyo"]}]'
Add-Diag $f 'ai-i1' '[{"type":"flow","title":"Hanya Zuwa General AI","items":["Narrow AI Yau","Machine Learning","Deep Learning","General AI Makoma"],"caption":"General AI har yanzu raayi ne"},{"type":"compare","title":"Narrow Da General","leftTitle":"Narrow","leftItems":["Aiki Daya","Yana Wanzuwa","Siri Da Alexa"],"rightTitle":"General","rightItems":["Kowane Fanni","Ba A Samu Ba","Raayi Ne"]},{"type":"hub","title":"Nauukan AI","center":"AI","satellites":["Narrow AI","ML","Deep Learning","General AI"]},{"type":"stack","title":"Juyin AI","items":["General AI","Deep Learning","Machine Learning","Dokoki"]}]'
Add-Diag $f 'ai-i2' '[{"type":"flow","title":"Matakan Machine Learning","items":["Tattara Bayanai","Shirya Bayanai","Horas Da Model","Gwadawa"],"caption":"ML yana koyo daga bayanai"},{"type":"compare","title":"Supervised Da Unsupervised","leftTitle":"Supervised","leftItems":["Bayanai Da Amsoshi","Rarrabuwa","Hasashe"],"rightTitle":"Unsupervised","rightItems":["Bayanai Kadai","Tara Juna","Gano Siffofi"]},{"type":"hub","title":"Amfani Da ML","center":"ML","satellites":["Hasashe","Rarrabuwa","Shawara","Gano Barazana"]},{"type":"stack","title":"Matakan ML","items":["Aiwatarwa","Horaswa","Shirya Siffofi","Tattara Bayanai"]}]'
Add-Diag $f 'ai-i3' '[{"type":"flow","title":"Amfani Da Kayan AI","items":["Zabi Kayan Aiki","Rubuta Tambaya","Duba Amsa","Yi Amfani Da Ita"],"caption":"Kayan AI suna taimakawa sosai"},{"type":"compare","title":"Rubutu Da Hoto","leftTitle":"Rubutu","leftItems":["ChatGPT","Takardu","Taimako A Rubutu"],"rightTitle":"Hoto","rightItems":["Midjourney","Zane","Taimako A Zane"]},{"type":"hub","title":"Kayan AI","center":"Tools","satellites":["ChatGPT","Midjourney","Grammarly","Copilot"]},{"type":"stack","title":"Matakan Kayan AI","items":["Interface","Model","Horaswa","Bayanai"]}]'
Add-Diag $f 'ai-i4' '[{"type":"flow","title":"AI A Aiki","items":["Gano Matsala","Zabi Kayan Aiki","Rubuta Tambaya","Yi Amfani Da Amsa"],"caption":"AI tana saurin kammala aiki"},{"type":"compare","title":"Da Hannu Da Da AI","leftTitle":"Da Hannu","leftItems":["Jinkiri","Gajiya","Kuskure"],"rightTitle":"Da AI","rightItems":["Sauri","Ba Gajiya","Daidaito"]},{"type":"hub","title":"AI A Aiki","center":"Aiki","satellites":["Rubutu","Takaitawa","Nazarin Bayanai","Shirye Shirye"]},{"type":"stack","title":"Aikace Aikace","items":["Automation","Taimako","Kirkire Kirkire","Bincike"]}]'
Add-Diag $f 'ai-i5' '[{"type":"flow","title":"Tunanin Da A A AI","items":["Gano Matsala","Nazarin Tasiri","Yanke Shawara","Sake Dubawa"],"caption":"Da a yana bukatar tunani mai zurfi"},{"type":"compare","title":"Adalci Da Son Zuciya","leftTitle":"Adalci","leftItems":["Ba Son Zuciya","Gaskiya","Daidaito"],"rightTitle":"Son Zuciya","rightItems":["Son Zuciya","Batanci","Rashin Daidaito"]},{"type":"hub","title":"Da A A AI","center":"Ethics","satellites":["Bias","Privacy","Deepfakes","Gaskiya"]},{"type":"stack","title":"Kaidojin Da A","items":["Manufofi","Dubawa","Sa Ido","Alhaki"]}]'
Add-Diag $f 'ai-i6' '[{"type":"flow","title":"AI Da Ayyuka","items":["Gano Canji","Koyon Sabuwar Fasaha","Gina Kwarewa","Neman Aiki"],"caption":"AI tana canza kasuwar aiki"},{"type":"compare","title":"Ayyuka Masu Raguwa Da Sabbi","leftTitle":"Masu Raguwa","leftItems":["Shigar Da Bayanai","Tallace Tallace Mai Sauki"],"rightTitle":"Sabbi","rightItems":["Prompt Engineer","AI Trainer","AI Ethics"]},{"type":"hub","title":"Sanaoin AI","center":"Aiki","satellites":["Prompt Engineer","ML Engineer","Data Scientist","AI Ethics"]},{"type":"stack","title":"Hanyar Aiki","items":["Kwarewa","Takarda","Aiki","Ci Gaba"]}]'
Add-Diag $f 'ai-a1' '[{"type":"flow","title":"Yadda Neural Network Ke Aiki","items":["Shigar Da Bayanai","Lissafi A Yadudduka","Gyara Kuskure","Bayar Da Amsa"],"caption":"Neural network tana koyo kamar kwakwalwa"},{"type":"compare","title":"Yadudduka Kadai Da Masu Yawa","leftTitle":"Kadai","leftItems":["Sauki","Matsala Mai Sauki","Sauri"],"rightTitle":"Masu Yawa","rightItems":["Rikici","Matsala Mai Wuya","Deep Learning"]},{"type":"hub","title":"Neural Networks","center":"Network","satellites":["Input Layer","Hidden Layers","Output","Weights"]},{"type":"stack","title":"Matakan Network","items":["Output","Hidden Layers","Input","Bayanai"]}]'
Add-Diag $f 'ai-a2' '[{"type":"flow","title":"Yadda LLM Ke Aiki","items":["Karban Rubutunka","Duba Mahalli","Hasashen Kalma","Maimaitawa Har Amsa"],"caption":"LLM tana gina jimla da hasashen kalma"},{"type":"compare","title":"LLM Da Na Baya","leftTitle":"Na Baya","leftItems":["Tsayi Daya","Babu Mahalli","Sauki"],"rightTitle":"LLM","rightItems":["Tsayi Da Yawa","Tana Da Mahalli","Rikici"]},{"type":"hub","title":"LLMs Shahararru","center":"LLM","satellites":["GPT-4","Claude","Gemini","Llama"]},{"type":"stack","title":"Matakan LLM","items":["Fine Tuning","Transformer","Horaswa","Tokenization"]}]'
Add-Diag $f 'ai-a3' '[{"type":"flow","title":"Yadda Generative AI Ke Aiki","items":["Karban Umarni","Fahimtar Nufi","Samar Da Abu","Nuna Sakamako"],"caption":"GenAI tana kirkirar sabbin abubuwa"},{"type":"compare","title":"GenAI Da AI Na Baya","leftTitle":"Na Baya","leftItems":["Gano Abubuwa","Rarrabuwa","Hasashe"],"rightTitle":"GenAI","rightItems":["Kirkirar Rubutu","Kirkirar Hoto","Kirkirar Bidiyo"]},{"type":"hub","title":"Generative AI","center":"GenAI","satellites":["Rubutu","Hoto","Sauti","Bidiyo"]},{"type":"stack","title":"Matakan GenAI","items":["Aikace Aikace","Models","Horaswa","Bayanai"]}]'
Add-Diag $f 'ai-a4' '[{"type":"flow","title":"Zaben Hanya","items":["Gano Manufa","Duba Bayanai","Zabi Hanya","Gwadawa"],"caption":"Zaben hanya ya dogara da manufa"},{"type":"compare","title":"Fine Tuning Da RAG","leftTitle":"Fine Tuning","leftItems":["Canza Model","Horas Da Sabuwa","Bukatar GPU"],"rightTitle":"RAG","rightItems":["Kara Bayanai","Ba A Canza Model","Mafi Araha"]},{"type":"hub","title":"Hanyoyi","center":"Model","satellites":["Fine Tuning","RAG","Prompting","Retrieval"]},{"type":"stack","title":"Matakan RAG","items":["Retrieval","Augmentation","Generation","Evaluation"]}]'
Add-Diag $f 'ai-a5' '[{"type":"flow","title":"Yadda AI Agent Ke Aiki","items":["An Bada Manufa","Ya Tsara Matakai","Ya Aiwatar","Ya Duba Sakamako"],"caption":"Agent yana aiki da kansa don manufa"},{"type":"compare","title":"Agent Da Chatbot","leftTitle":"Chatbot","leftItems":["Amsa Tambaya","Ba Ya Yin Aiki","Sauki"],"rightTitle":"Agent","rightItems":["Yana Yin Aiki","Yana Shawara","Rikici"]},{"type":"hub","title":"AI Agents","center":"Agent","satellites":["Planning","Tool Use","Memory","Reasoning"]},{"type":"stack","title":"Matakan Agent","items":["Action","Planning","LLM Core","Memory"]}]'
Add-Diag $f 'ai-a6' '[{"type":"flow","title":"Hanya Zuwa Sanaa A AI","items":["Koyon Fasaha","Ginawa Da Kayan Aiki","Shirya Takarda","Neman Aiki"],"caption":"Sanaoin AI suna bukatar kwarewa"},{"type":"compare","title":"Masu Rubutu Da Masu Fasaha","leftTitle":"Masu Rubutu","leftItems":["Prompt Engineer","Marubuci","Mai Kirkire"],"rightTitle":"Masu Fasaha","rightItems":["ML Engineer","Data Scientist","Mai Bincike"]},{"type":"hub","title":"Sanaoin AI","center":"Careers","satellites":["Prompt Engineer","ML Engineer","Data Scientist","Product Manager"]},{"type":"stack","title":"Matakan Sanaa","items":["Shugabanci","Product","Engineering","Bincike"]}]'
Write-Output "AI DONE"
