$ErrorActionPreference = "Stop"
$targetDir = "C:\Users\LAB\Desktop\Hausa Tech\TechHausa\TechHausa\app\src\main\assets\courses"
function Add-Diag {
    param($file, $id, $diag)
    $raw = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8)
    $search = '"id": "' + $id + '"'
    $idPos = $raw.IndexOf($search)
    if ($idPos -lt 0) { Write-Output ("SKIP " + $id); return }
    $quizPos = $raw.IndexOf('"quiz":', $idPos)
    if ($quizPos -lt 0) { Write-Output ("NOQUIZ " + $id); return }
    $raw = $raw.Insert($quizPos, '            "supplementaryDiagrams": ' + $diag + ",`n")
    [System.IO.File]::WriteAllText($file, $raw, [System.Text.Encoding]::UTF8)
    Write-Output ("OK " + $id)
}
$f = "$targetDir\cloud_computing.json"
Add-Diag $f 'cloud-b1' '[{"type":"flow","title":"Yadda Cloud Ke Aiki","items":["Naura Ta Nemi","Intanet Ya Kai","Server Ya Amsa","Sakamako Ya Dawo"],"caption":"Cloud haya ce ta kwamfuta a intanet"},{"type":"compare","title":"Cloud Da Kwamfuta","leftTitle":"Kwamfuta","leftItems":["Guda Daya","Kana Saya","Kulawa Da Kanka"],"rightTitle":"Cloud","rightItems":["Da Yawa","Haya","Su Suna Kulawa"]},{"type":"hub","title":"Cloud","center":"Cloud","satellites":["Ajiya","Server","Software","Database"]},{"type":"stack","title":"Matakan Cloud","items":["App","Platform","Hardware","Cibiya"]}]'
Add-Diag $f 'cloud-b2' '[{"type":"flow","title":"Zaben Sabis","items":["Gano Bukata","Kwatanta Nauuka","Zabi Daya","Fara Amfani"],"caption":"IaaS PaaS SaaS kowane da amfani"},{"type":"compare","title":"IaaS Da SaaS","leftTitle":"IaaS","leftItems":["Haya Hardware","Kai Kana Gina","Misali AWS EC2"],"rightTitle":"SaaS","rightItems":["Shirin Software","Kai Kana Amfani","Misali Gmail"]},{"type":"hub","title":"Nauukan Sabis","center":"Sabis","satellites":["IaaS","PaaS","SaaS","Serverless"]},{"type":"stack","title":"Matakan Sabis","items":["SaaS","PaaS","IaaS","Hardware"]}]'
Add-Diag $f 'cloud-b3' '[{"type":"flow","title":"Zaben Kamfani","items":["Lissafa Kamfanoni","Kwatanta Farashi","Gwada Kyauta","Zabi Daya"],"caption":"AWS Azure Google sune manya"},{"type":"compare","title":"AWS Da Azure","leftTitle":"AWS","leftItems":["Amazon","Mafi Girma"],"rightTitle":"Azure","rightItems":["Microsoft","Yana Hadawa Da Office"]},{"type":"hub","title":"Kamfanonin Cloud","center":"Cloud","satellites":["AWS","Azure","Google Cloud","Oracle"]},{"type":"stack","title":"Matakan Kamfani","items":["Sabis","Yanki","Farashi","Tsaro"]}]'
Add-Diag $f 'cloud-b4' '[{"type":"flow","title":"Amfanin Cloud","items":["Babu Saya Hardware","Biya Gwargwadon Amfani","Karuwa Lokacin Bukata","Samuwa Ko Ina"],"caption":"Cloud tana saurin kasuwanci"},{"type":"compare","title":"Cloud Da Server Na Gida","leftTitle":"Na Gida","leftItems":["Saya Da Tsada","Kulawa Da Kanka","Iyaka"],"rightTitle":"Cloud","rightItems":["Araha","Su Suna Kulawa","Ba Iyaka"]},{"type":"hub","title":"Amfani","center":"Cloud","satellites":["Araha","Sauri","Tsaro","Samuwa"]},{"type":"stack","title":"Fa idodi","items":["Samuwa","Tsaro","Sauri","Araha"]}]'
Add-Diag $f 'cloud-b5' '[{"type":"flow","title":"Ajiya A Cloud","items":["Zabi Sabis","Loda Fayil","Ajiye Laipiya","Sauke Ko Yaushe"],"caption":"Fayilolinka suna lafiya a cloud"},{"type":"compare","title":"Cloud Da Flash","leftTitle":"Flash","leftItems":["Zai Iya Bacewa","Wuri Daya"],"rightTitle":"Cloud","rightItems":["Kwafi Da Yawa","Ko Ina"]},{"type":"hub","title":"Ajiya","center":"Storage","satellites":["Google Drive","Dropbox","OneDrive","S3"]},{"type":"stack","title":"Matakan Ajiya","items":["App","Sabis","Cibiya","Kwafi"]}]'
Add-Diag $f 'cloud-b6' '[{"type":"flow","title":"Farawa Da Cloud","items":["Bude Asusu","Zabi Sabis Kyauta","Bi Koyarwa","Gina Abu Mai Sauki"],"caption":"Fara da kyauta kuma koyo kadan kadan"},{"type":"compare","title":"Kyauta Da Biya","leftTitle":"Kyauta","leftItems":["Iyaka","Na Koyo"],"rightTitle":"Biya","rightItems":["Ba Iyaka","Na Kasuwanci"]},{"type":"hub","title":"Farawa","center":"Fara","satellites":["Asusu","Console","Koyarwa","Project"]},{"type":"stack","title":"Matakan Farawa","items":["Gina","Koyarwa","Sabis","Asusu"]}]'
Add-Diag $f 'cloud-i1' '[{"type":"flow","title":"Virtualization","items":["Hardware Daya","Raba Gida Da Yawa","Kowane Yana Aiki","Amfani Da Duk"],"caption":"Kwamfuta daya tana kamar da yawa"},{"type":"compare","title":"VM Da Container","leftTitle":"VM","leftItems":["Nauyi","Kowane Da OS"],"rightTitle":"Container","rightItems":["Sauki","Docker"]},{"type":"hub","title":"Virtualization","center":"VM","satellites":["Hypervisor","VM","Container","Docker"]},{"type":"stack","title":"Matakan VM","items":["App","Container","VM","Hardware"]}]'
Add-Diag $f 'cloud-i2' '[{"type":"flow","title":"Scalability","items":["Bukata Ta Karu","Kara Naurori","Bukata Ta Ragu","Rage Naurori"],"caption":"Cloud tana karuwa da raguwa da kanta"},{"type":"compare","title":"Scalability Da Elasticity","leftTitle":"Scalability","leftItems":["Iya Karuwa","Tsari"],"rightTitle":"Elasticity","rightItems":["Karuwa Da Kanta","Atomatik"]},{"type":"hub","title":"Karuwa","center":"Scale","satellites":["Auto Scale","Load Balancer","Monitor","Alert"]},{"type":"stack","title":"Matakan Scale","items":["Balancer","Servers","Monitor","App"]}]'
Add-Diag $f 'cloud-i3' '[{"type":"flow","title":"Hijira Zuwa Cloud","items":["Bincika Abin Da Ake Da Shi","Tsara Hijira","Matsar Kadan Kadan","Tabbatarwa"],"caption":"Hijira a hankali tana rage hatsari"},{"type":"compare","title":"Duk Lokaci Daya Da Kadan Kadan","leftTitle":"Duk Daya","leftItems":["Sauri","Hatsari"],"rightTitle":"Kadan Kadan","rightItems":["Jinkiri","Lafiya"]},{"type":"hub","title":"Hijira","center":"Migrate","satellites":["Tsari","Matsarwa","Gwaji","Horawa"]},{"type":"stack","title":"Matakan Hijira","items":["Ingantawa","Tabbatarwa","Matsarwa","Bincike"]}]'
Add-Diag $f 'cloud-i4' '[{"type":"flow","title":"Sarrafa Kudi","items":["Duba Lissafi","Gano Barnatarwa","Kashe Abin Da Ba A Amfani","Saka Iyaka"],"caption":"Kudi suna tafiya idan ba sa ido"},{"type":"compare","title":"Biya Gwargwado Da Tsayayye","leftTitle":"Gwargwado","leftItems":["Biya Abin Da Ka Amfani","Canjawa"],"rightTitle":"Tsayayye","rightItems":["Kudi Daya","Ba Canjawa"]},{"type":"hub","title":"Kudi","center":"Cost","satellites":["Billing","Alert","Rightsize","Reserved"]},{"type":"stack","title":"Matakan Kudi","items":["Ingantawa","Iyaka","Sa Ido","Lissafi"]}]'
Add-Diag $f 'cloud-i5' '[{"type":"flow","title":"API Da Cloud","items":["App Ta Kira API","Cloud Ya Amsa","Bayanai Sun Dawo","App Ta Nuna"],"caption":"APIs suna hada cloud da apps"},{"type":"compare","title":"API Da Dashboard","leftTitle":"API","leftItems":["Don Code","Atomatik"],"rightTitle":"Dashboard","rightItems":["Don Mutum","Da Hannu"]},{"type":"hub","title":"Hadi","center":"API","satellites":["REST","SDK","Webhook","CLI"]},{"type":"stack","title":"Matakan Hadi","items":["App","API","Sabis","Bayanai"]}]'
Add-Diag $f 'cloud-i6' '[{"type":"flow","title":"Multi Cloud","items":["Amfani Da AWS","Amfani Da Azure","Hada Su","Raba Hatsari"],"caption":"Kada a dogara ga daya kadai"},{"type":"compare","title":"Multi Da Hybrid","leftTitle":"Multi","leftItems":["Cloud Da Yawa","Raba Hatsari"],"rightTitle":"Hybrid","rightItems":["Gida Da Cloud","A Hankali"]},{"type":"hub","title":"Dabaru","center":"Cloud","satellites":["AWS","Azure","Gida","Hadi"]},{"type":"stack","title":"Matakan Dabara","items":["Gudanarwa","Hadi","Cloud","Gida"]}]'
Add-Diag $f 'cloud-a1' '[{"type":"flow","title":"Yadda Kubernetes Ke Aiki","items":["Shirya Container","Tura Zuwa Cluster","Kubernetes Ya Raba","Sa Ido Da Gyara"],"caption":"Kubernetes mai kula da containers"},{"type":"compare","title":"Docker Da Kubernetes","leftTitle":"Docker","leftItems":["Container Daya","Gina"],"rightTitle":"Kubernetes","rightItems":["Da Yawa","Gudanarwa"]},{"type":"hub","title":"Kubernetes","center":"K8s","satellites":["Pods","Nodes","Services","Deploy"]},{"type":"stack","title":"Matakan K8s","items":["App","Pods","Nodes","Hardware"]}]'
Add-Diag $f 'cloud-a2' '[{"type":"flow","title":"Serverless","items":["Rubuta Aiki","Loda Shi","Yana Gudana Lokacin Nemi","Biya Lokacin Gudana"],"caption":"Ba server a gani ba server a biya"},{"type":"compare","title":"Serverless Da Server","leftTitle":"Server","leftItems":["Kullum Yana Gudana","Biya Kullum"],"rightTitle":"Serverless","rightItems":["Lokacin Nemi Kadai","Biya Kadai"]},{"type":"hub","title":"Serverless","center":"Lambda","satellites":["Functions","Events","API Gateway","Biya"]},{"type":"stack","title":"Matakan Serverless","items":["Aiki","Event","Platform","Biya"]}]'
Add-Diag $f 'cloud-a3' '[{"type":"flow","title":"Tsarin Architecture","items":["Gano Bukata","Zana Tsari","Zabi Sabis","Gina Kuma Gwada"],"caption":"Tsari mai kyau yana rage kudi"},{"type":"compare","title":"Monolith Da Microservices","leftTitle":"Monolith","leftItems":["Duk Tare","Sauki Na Farko"],"rightTitle":"Microservices","rightItems":["Rarrabe","Mafi Kyau Babba"]},{"type":"hub","title":"Architecture","center":"Tsari","satellites":["Frontend","API","Services","DB"]},{"type":"stack","title":"Matakan Tsari","items":["CDN","App","Services","Database"]}]'
Add-Diag $f 'cloud-a4' '[{"type":"flow","title":"CI CD","items":["Rubuta Code","Test Da Kanta","Tura Atomatik","Sa Ido"],"caption":"CI CD tana tura code da sauri"},{"type":"compare","title":"Da Hannu Da Atomatik","leftTitle":"Da Hannu","leftItems":["Jinkiri","Kuskure"],"rightTitle":"Atomatik","rightItems":["Sauri","Daidaito"]},{"type":"hub","title":"DevOps","center":"CI CD","satellites":["Git","Test","Build","Deploy"]},{"type":"stack","title":"Matakan CI CD","items":["Deploy","Build","Test","Code"]}]'
Add-Diag $f 'cloud-a5' '[{"type":"flow","title":"Cloud Databases","items":["Zabi Naui","Kirkiri Database","Hada Da App","Ajiye Kwafi"],"caption":"Database a cloud ba kulawa"},{"type":"compare","title":"Managed Da Self Hosted","leftTitle":"Managed","leftItems":["Su Suna Kulawa","Araha Lokaci"],"rightTitle":"Self Hosted","rightItems":["Kai Kana Kulawa","Iko Mai Yawa"]},{"type":"hub","title":"Databases","center":"DB","satellites":["RDS","Firestore","Cosmos","DynamoDB"]},{"type":"stack","title":"Matakan DB","items":["App","Connection","Database","Kwafi"]}]'
Add-Diag $f 'cloud-a6' '[{"type":"flow","title":"Hanya Zuwa Cloud Career","items":["Koyon Asali","Gina Project","Shirya Takarda","Neman Aiki"],"caption":"Takarda da project suna bude kofa"},{"type":"compare","title":"Architect Da Engineer","leftTitle":"Architect","leftItems":["Tsari","Zane"],"rightTitle":"Engineer","rightItems":["Gina","Aiki"]},{"type":"hub","title":"Sanaoin Cloud","center":"Career","satellites":["Architect","Engineer","DevOps","Security"]},{"type":"stack","title":"Matakan Sanaa","items":["Senior","Mid","Junior","Farkon Koyo"]}]'
Write-Output "CLOUD DONE"
