$ErrorActionPreference = "Stop"
$targetDir = "C:\Users\LAB\Desktop\Hausa Tech\TechHausa\TechHausa\app\src\main\assets\courses"
function Add-Diag {
    param($file, $id, $diag)
    $raw = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8)
    $search = '"id": "' + $id + '"'
    $idPos = $raw.IndexOf($search)
    if ($idPos -lt 0) { Write-Output ("SKIP " + $id); return }
    $quizPos = $raw.IndexOf('"quiz":', $idPos)
    if ($quizPos -lt 0) { Write-Output ("NOQUIZ " + $id); return }
    $raw = $raw.Insert($quizPos, '            "supplementaryDiagrams": ' + $diag + ",`n")
    [System.IO.File]::WriteAllText($file, $raw, [System.Text.Encoding]::UTF8)
    Write-Output ("OK " + $id)
}
$f = "$targetDir\data_science.json"
Add-Diag $f 'ds-b1' '[{"type":"flow","title":"Yadda Data Science Ke Aiki","items":["Tattara Bayanai","Tsarkake Su","Nazarin Su","Bayar Da Shawara"],"caption":"Data science labari ne daga lambobi"},{"type":"compare","title":"Raayi Da Bayanai","leftTitle":"Raayi","leftItems":["Zato","Zai Iya Kuskure"],"rightTitle":"Bayanai","rightItems":["Gaskiya","Daidaito"]},{"type":"hub","title":"Data Science","center":"Data","satellites":["Bayanai","Lissafi","Kwatance","Shawara"]},{"type":"stack","title":"Matakan Aiki","items":["Shawara","Kwatance","Tsarkakewa","Tattarawa"]}]'
Add-Diag $f 'ds-b2' '[{"type":"flow","title":"Nauukan Bayanai","items":["Gano Tushe","Rarraba Naui","Adana Su","Yi Amfani"],"caption":"Bayanai suna zuwa da nauuka daban"},{"type":"compare","title":"Lambobi Da Rubutu","leftTitle":"Lambobi","leftItems":["Kididdiga","Misali Shekaru"],"rightTitle":"Rubutu","rightItems":["Kalmomi","Misali Suna"]},{"type":"hub","title":"Bayanai","center":"Data","satellites":["Lambobi","Rubutu","Hoto","Sauti"]},{"type":"stack","title":"Matakan Bayanai","items":["Amfani","Adanawa","Rarrabuwa","Tushe"]}]'
Add-Diag $f 'ds-b3' '[{"type":"flow","title":"Amfani Da Excel","items":["Bude Takarda","Shigar Da Bayanai","Yi Lissafi","Zana Jadawali"],"caption":"Excel makaranta ce ta data"},{"type":"compare","title":"Da Hannu Da Formula","leftTitle":"Da Hannu","leftItems":["Jinkiri","Kuskure"],"rightTitle":"Formula","rightItems":["Sauri","Daidaito"]},{"type":"hub","title":"Excel","center":"Excel","satellites":["Rows","Columns","Formulas","Charts"]},{"type":"stack","title":"Matakan Excel","items":["Jadawali","Formula","Bayanai","Takarda"]}]'
Add-Diag $f 'ds-b4' '[{"type":"flow","title":"Kwatancen Bayanai","items":["Zabi Bayanai","Zabi Jadawali","Zana Shi","Fassara Shi"],"caption":"Hoto yana magana fiye da lambobi"},{"type":"compare","title":"Teburi Da Jadawali","leftTitle":"Teburi","leftItems":["Lambobi","Wuya A Gani"],"rightTitle":"Jadawali","rightItems":["Hoto","Saukin Gani"]},{"type":"hub","title":"Visualization","center":"Gani","satellites":["Bar Chart","Line","Pie","Map"]},{"type":"stack","title":"Matakan Kwatance","items":["Fassara","Zana","Zabi","Bayanai"]}]'
Add-Diag $f 'ds-b5' '[{"type":"flow","title":"Kididdiga A Sauki","items":["Tattara Lambobi","Nemo Matsakaici","Duba Bambanci","Yanke Shawara"],"caption":"Statistics takaitawa ce ta bayanai"},{"type":"compare","title":"Matsakaici Da Yawa","leftTitle":"Matsakaici","leftItems":["Daraja Daya","Takaitawa"],"rightTitle":"Duka","rightItems":["Da Yawa","Cikakke"]},{"type":"hub","title":"Statistics","center":"Stats","satellites":["Mean","Median","Yawa","Bambanci"]},{"type":"stack","title":"Matakan Stats","items":["Shawara","Bambanci","Takaitawa","Bayanai"]}]'
Add-Diag $f 'ds-b6' '[{"type":"flow","title":"Farawa Da Python","items":["Sanya Python","Koyon Asali","Gwada Pandas","Nazarin Bayanai"],"caption":"Python yaren data ne"},{"type":"compare","title":"Excel Da Python","leftTitle":"Excel","leftItems":["Sauki","Kadan"],"rightTitle":"Python","rightItems":["Mai Iko","Da Yawa"]},{"type":"hub","title":"Python","center":"Python","satellites":["Pandas","Numpy","Charts","ML"]},{"type":"stack","title":"Matakan Python","items":["ML","Charts","Pandas","Asali"]}]'
Add-Diag $f 'ds-i1' '[{"type":"flow","title":"Tsarkake Bayanai","items":["Nemo Gurbatattun","Cire Kwafi","Cika Gurbi","Tabbatarwa"],"caption":"Bayanai masu tsafta sakamako mai tsafta"},{"type":"compare","title":"Mai Tsafta Da Gurbatacce","leftTitle":"Mai Tsafta","leftItems":["Daidaito","Amintacce"],"rightTitle":"Gurbatacce","rightItems":["Kuskure","Bata Lokaci"]},{"type":"hub","title":"Cleaning","center":"Tsafta","satellites":["Kwafi","Gurbi","Kuskure","Tabbaci"]},{"type":"stack","title":"Matakan Tsafta","items":["Tabbaci","Cikawa","Cirewa","Bincike"]}]'
Add-Diag $f 'ds-i2' '[{"type":"flow","title":"Yadda SQL Ke Aiki","items":["Rubuta Tambaya","Aika Zuwa DB","DB Ta Nemo","Amsa Ta Dawo"],"caption":"SQL yaren tambayar database"},{"type":"compare","title":"SELECT Da INSERT","leftTitle":"SELECT","leftItems":["Neman Bayanai","Karatu"],"rightTitle":"INSERT","rightItems":["Saka Bayanai","Rubutu"]},{"type":"hub","title":"SQL","center":"SQL","satellites":["SELECT","WHERE","JOIN","GROUP BY"]},{"type":"stack","title":"Matakan SQL","items":["Amsa","Tambaya","Teburi","Database"]}]'
Add-Diag $f 'ds-i3' '[{"type":"flow","title":"ML Don Data","items":["Shirya Bayanai","Horas Da Model","Gwada Shi","Hasashe"],"caption":"ML yana hasashe daga tarihi"},{"type":"compare","title":"Hasashe Da Rarrabuwa","leftTitle":"Hasashe","leftItems":["Lamba","Misali Farashi"],"rightTitle":"Rarrabuwa","rightItems":["Rukuni","Misali Nagari Mara Kyau"]},{"type":"hub","title":"ML","center":"ML","satellites":["Hasashe","Rarrabuwa","Tara","Gwaji"]},{"type":"stack","title":"Matakan ML","items":["Hasashe","Gwaji","Horaswa","Bayanai"]}]'
Add-Diag $f 'ds-i4' '[{"type":"flow","title":"A B Testing","items":["Raba Masu Amfani","Nuna A Da B","Auna Sakamako","Zabi Mai Nasara"],"caption":"Gwaji yana bada gaskiya ba zato"},{"type":"compare","title":"A Da B","leftTitle":"A","leftItems":["Tsohuwa","Misali Blue"],"rightTitle":"B","rightItems":["Sabuwa","Misali Red"]},{"type":"hub","title":"Testing","center":"Test","satellites":["Rukuni A","Rukuni B","Aunawa","Shawara"]},{"type":"stack","title":"Matakan Test","items":["Shawara","Aunawa","Gwajin","Raba"]}]'
Add-Diag $f 'ds-i5' '[{"type":"flow","title":"Gina Dashboard","items":["Hada Bayanai","Zabi Jadawali","Tsara Shafi","Wallafa"],"caption":"Dashboard taga ce ga kasuwanci"},{"type":"compare","title":"Dashboard Da Rahoto","leftTitle":"Dashboard","leftItems":["Rayayye","Kullum"],"rightTitle":"Rahoto","rightItems":["Tsaye","Lokaci Daya"]},{"type":"hub","title":"Dashboard","center":"Board","satellites":["Charts","KPIs","Filters","Share"]},{"type":"stack","title":"Matakan Board","items":["Wallafa","Tsarawa","Jadawali","Bayanai"]}]'
Add-Diag $f 'ds-i6' '[{"type":"flow","title":"Da A A Bayanai","items":["Tattara Da Izini","Boye Sirri","Yi Adalci","Bayyana Hanyoyi"],"caption":"Bayanai na mutane nauyi ne"},{"type":"compare","title":"Sirri Da Bayyananne","leftTitle":"Sirri","leftItems":["Kare","Izini"],"rightTitle":"Bayyananne","rightItems":["Bude","Ba Sirri"]},{"type":"hub","title":"Ethics","center":"Da A","satellites":["Sirri","Izini","Adalci","Bayyana"]},{"type":"stack","title":"Matakan Da A","items":["Bayyana","Adalci","Sirri","Izini"]}]'
Add-Diag $f 'ds-a1' '[{"type":"flow","title":"Big Data","items":["Tattara Masu Yawa","Ajiye A Gungu","Sarrafa Da Kayan Aiki","Fitar Da Fahimta"],"caption":"Big data teku ne na bayanai"},{"type":"compare","title":"Karami Da Babba","leftTitle":"Karami","leftItems":["Excel Ya Isa","Sauki"],"rightTitle":"Babba","rightItems":["Kayan Musamman","Spark"]},{"type":"hub","title":"Big Data","center":"Big","satellites":["Girma","Sauri","Nauuka","Spark"]},{"type":"stack","title":"Matakan Big","items":["Fahimta","Sarrafa","Ajiya","Tattarawa"]}]'
Add-Diag $f 'ds-a2' '[{"type":"flow","title":"Predictive Modeling","items":["Tattara Tarihi","Gina Model","Gwada Hasashe","Aiwatar"],"caption":"Tarihi yana koyar da gaba"},{"type":"compare","title":"Bayani Da Hasashe","leftTitle":"Bayani","leftItems":["Abin Da Ya Faru","Tarihi"],"rightTitle":"Hasashe","rightItems":["Abin Da Zai Faru","Gaba"]},{"type":"hub","title":"Hasashe","center":"Predict","satellites":["Tarihi","Model","Gwaji","Hasashe"]},{"type":"stack","title":"Matakan Hasashe","items":["Aiwatar","Gwaji","Model","Tarihi"]}]'
Add-Diag $f 'ds-a3' '[{"type":"flow","title":"Deep Learning","items":["Shirya Bayanai Masu Yawa","Gina Network","Horaswa","Hasashe Mai Zurfi"],"caption":"Deep learning don hotuna da sauti"},{"type":"compare","title":"ML Da Deep","leftTitle":"ML","leftItems":["Kadan","Sauki"],"rightTitle":"Deep","rightItems":["Masu Yawa","Rikici"]},{"type":"hub","title":"Deep","center":"Neural","satellites":["Hoto","Sauti","Rubutu","GPU"]},{"type":"stack","title":"Matakan Deep","items":["Hasashe","Horaswa","Network","Bayanai"]}]'
Add-Diag $f 'ds-a4' '[{"type":"flow","title":"Data Engineering","items":["Tattara Daga Tushe","Canza Tsari","Ajiye A Rumbun","Bayar Da Shi"],"caption":"Engineering bututu ne na bayanai"},{"type":"compare","title":"Nazarin Da Injiniya","leftTitle":"Nazarin","leftItems":["Fassara","Shawara"],"rightTitle":"Injiniya","rightItems":["Gina Bututu","Samarwa"]},{"type":"hub","title":"Engineering","center":"Pipeline","satellites":["Tattarawa","Canzawa","Ajiya","Bayarwa"]},{"type":"stack","title":"Matakan Pipeline","items":["Bayarwa","Ajiya","Canzawa","Tattarawa"]}]'
Add-Diag $f 'ds-a5' '[{"type":"flow","title":"Nazarin Kasuwanci","items":["Tambayi Tambaya","Tattara Bayanai","Nazarin","Shawara Ga Shugaba"],"caption":"Data tana jagorantar kasuwanci"},{"type":"compare","title":"Zato Da Gaskiya","leftTitle":"Zato","leftItems":["Raayi","Hatsari"],"rightTitle":"Gaskiya","rightItems":["Bayanai","Lafiya"]},{"type":"hub","title":"Kasuwanci","center":"Biz","satellites":["Sayarwa","Abokan Ciniki","Kudi","Shawara"]},{"type":"stack","title":"Matakan Nazarin","items":["Shawara","Nazarin","Bayanai","Tambaya"]}]'
Add-Diag $f 'ds-a6' '[{"type":"flow","title":"Hanya Zuwa Data Career","items":["Koyon Excel","Koyon SQL Python","Gina Projects","Neman Aiki"],"caption":"Projects suna nuna kwarewa"},{"type":"compare","title":"Analyst Da Scientist","leftTitle":"Analyst","leftItems":["Bayani","Dashboard"],"rightTitle":"Scientist","rightItems":["Hasashe","ML"]},{"type":"hub","title":"Sanaoin Data","center":"Career","satellites":["Analyst","Scientist","Engineer","ML"]},{"type":"stack","title":"Matakan Sanaa","items":["Senior","Mid","Junior","Farkon Koyo"]}]'
Write-Output "DS DONE"
