$ErrorActionPreference = "Stop"
$targetDir = "C:\Users\LAB\Desktop\Hausa Tech\TechHausa\TechHausa\app\src\main\assets\courses"
function Add-Diag {
    param($file, $id, $diag)
    $raw = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8)
    $search = '"id": "' + $id + '"'
    $idPos = $raw.IndexOf($search)
    if ($idPos -lt 0) { Write-Output ("SKIP " + $id); return }
    $quizPos = $raw.IndexOf('"quiz":', $idPos)
    if ($quizPos -lt 0) { Write-Output ("NOQUIZ " + $id); return }
    $raw = $raw.Insert($quizPos, '            "supplementaryDiagrams": ' + $diag + ",`n")
    [System.IO.File]::WriteAllText($file, $raw, [System.Text.Encoding]::UTF8)
    Write-Output ("OK " + $id)
}
$f = "$targetDir\mobile_development.json"
Add-Diag $f 'mob-b1' '[{"type":"flow","title":"Yadda App Ke Aiki","items":["Bude App","App Ta Nemi Bayanai","Server Ya Amsa","Nuna Sakamako"],"caption":"App taga ce ga intanet"},{"type":"compare","title":"App Da Shafi","leftTitle":"App","leftItems":["Sawa","Sauri"],"rightTitle":"Shafi","rightItems":["Browser","Jinkiri"]},{"type":"hub","title":"Mobile","center":"App","satellites":["Android","iOS","Store","User"]},{"type":"stack","title":"Matakan App","items":["UI","Logic","API","Server"]}]'
Add-Diag $f 'mob-b2' '[{"type":"flow","title":"Zaben Platform","items":["Duba Kasuwa","Kwatanta Android iOS","Zabi Daya","Fara Koyo"],"caption":"Android ya fi yawa a Najeriya"},{"type":"compare","title":"Android Da iOS","leftTitle":"Android","leftItems":["Google","Araha","Masu Yawa"],"rightTitle":"iOS","rightItems":["Apple","Tsada","Kadan"]},{"type":"hub","title":"Platforms","center":"OS","satellites":["Android","iOS","Store","User"]},{"type":"stack","title":"Matakan Zabi","items":["Kwarewa","Kasuwa","Farashi","Manufa"]}]'
Add-Diag $f 'mob-b3' '[{"type":"flow","title":"Native Da Cross","items":["Gano Manufa","Kwatanta Hanyoyi","Zabi Daya","Gina App"],"caption":"Cross yana rubuta sau daya"},{"type":"compare","title":"Native Da Cross","leftTitle":"Native","leftItems":["Sauri","Kotlin Swift"],"rightTitle":"Cross","rightItems":["Sau Daya","Flutter"]},{"type":"hub","title":"Hanyoyi","center":"Dev","satellites":["Kotlin","Swift","Flutter","React Native"]},{"type":"stack","title":"Matakan Gina","items":["Buga","Gwaji","Code","Zabi"]}]'
Add-Diag $f 'mob-b4' '[{"type":"flow","title":"UI UX Mai Kyau","items":["Shirya Zane","Saka Button A Wuri","Gwada Da Mutane","Gyara"],"caption":"Design mai sauki yana rike masu amfani"},{"type":"compare","title":"Mai Kyau Da Mara Kyau","leftTitle":"Mai Kyau","leftItems":["Sauki","Bayyana"],"rightTitle":"Mara Kyau","rightItems":["Rikici","Bata"]},{"type":"hub","title":"Design","center":"UI","satellites":["Button","Launi","Font","Hoto"]},{"type":"stack","title":"Matakan Design","items":["Gwaji","Zane","Tsari","Bincike"]}]'
Add-Diag $f 'mob-b5' '[{"type":"flow","title":"Kayan Aiki","items":["Sanya Studio","Bude Project","Rubuta Code","Gudanar Da Emulator"],"caption":"Android Studio gida ne na app"},{"type":"compare","title":"Emulator Da Waya","leftTitle":"Emulator","leftItems":["A Kwamfuta","Na Gwaji"],"rightTitle":"Waya","rightItems":["Ainihi","Na Gaskiya"]},{"type":"hub","title":"Tools","center":"Studio","satellites":["Code","Emulator","Debug","Build"]},{"type":"stack","title":"Matakan Aiki","items":["Build","Debug","Code","Sanya"]}]'
Add-Diag $f 'mob-b6' '[{"type":"flow","title":"App Na Farko","items":["Kirkiri Project","Zana Fuska Daya","Kara Button","Gudanarwa"],"caption":"Fara karami kuma yi alfahari"},{"type":"compare","title":"Sauki Da Rikici","leftTitle":"Sauki","leftItems":["Fuska Daya","Na Farko"],"rightTitle":"Rikici","rightItems":["Da Yawa","Daga Baya"]},{"type":"hub","title":"App Farko","center":"Hello","satellites":["Layout","Button","Text","Run"]},{"type":"stack","title":"Matakan App","items":["Run","Button","Layout","Project"]}]'
Add-Diag $f 'mob-i1' '[{"type":"flow","title":"Flutter Da React Native","items":["Koyon Daya","Rubuta Code","Gina Na Android iOS","Buga Biyu"],"caption":"Code daya app biyu"},{"type":"compare","title":"Flutter Da React Native","leftTitle":"Flutter","leftItems":["Dart","Google"],"rightTitle":"React Native","rightItems":["JavaScript","Meta"]},{"type":"hub","title":"Cross","center":"Code Daya","satellites":["Flutter","React Native","Android","iOS"]},{"type":"stack","title":"Matakan Cross","items":["Buga","Build","Code","Zabi"]}]'
Add-Diag $f 'mob-i2' '[{"type":"flow","title":"Ajiya A Waya","items":["Zabi Wuri","Ajiye Bayanai","Karanta Lokacin Bukata","Share Tsohuwa"],"caption":"Waya tana rike bayanai a ciki"},{"type":"compare","title":"Ciki Da Cloud","leftTitle":"Ciki","leftItems":["Ba Intanet","Sauri"],"rightTitle":"Cloud","rightItems":["Intanet","Ko Ina"]},{"type":"hub","title":"Ajiya","center":"Store","satellites":["Preferences","Database","Fayil","Cloud"]},{"type":"stack","title":"Matakan Ajiya","items":["Cloud","Database","Fayil","App"]}]'
Add-Diag $f 'mob-i3' '[{"type":"flow","title":"API A Mobile","items":["App Ta Nemi","Intanet Ya Kai","Server Ya Amsa","App Ta Nuna"],"caption":"API tana ciyar da app da bayanai"},{"type":"compare","title":"Online Da Offline","leftTitle":"Online","leftItems":["Sabuntawa","Intanet"],"rightTitle":"Offline","rightItems":["Tsohuwa","Ba Intanet"]},{"type":"hub","title":"Backend","center":"API","satellites":["GET","POST","JSON","Auth"]},{"type":"stack","title":"Matakan API","items":["Nuna","Amsa","Nemi","App"]}]'
Add-Diag $f 'mob-i4' '[{"type":"flow","title":"Gwaji Da Debugging","items":["Gudanar Da App","Nemo Kuskure","Karanta Log","Gyara Kuma Gwada"],"caption":"Gwaji a waya ta gaskiya ma da kyau"},{"type":"compare","title":"Emulator Da Waya","leftTitle":"Emulator","leftItems":["Sauki","Ba Kudi"],"rightTitle":"Waya","rightItems":["Gaskiya","Mafi Kyau"]},{"type":"hub","title":"Gwaji","center":"Test","satellites":["Emulator","Waya","Log","Gyara"]},{"type":"stack","title":"Matakan Gwaji","items":["Gyara","Log","Gwajin","Code"]}]'
Add-Diag $f 'mob-i5' '[{"type":"flow","title":"Buga App","items":["Shirya App","Bude Asusun Developer","Loda App","Jira Amincewa"],"caption":"Store kasuwa ce ta apps"},{"type":"compare","title":"Play Da App Store","leftTitle":"Play","leftItems":["Google","Araha"],"rightTitle":"App Store","rightItems":["Apple","Tsada"]},{"type":"hub","title":"Store","center":"Buga","satellites":["Play","App Store","Icon","Bayani"]},{"type":"stack","title":"Matakan Buga","items":["Wallafa","Amincewa","Lodawa","Shiri"]}]'
Add-Diag $f 'mob-i6' '[{"type":"flow","title":"Samun Kudi Daga App","items":["Gina Masu Amfani","Zabi Hanya","Saka Talla Ko Biya","Karba Kudi"],"caption":"Masu amfani da yawa kudi da yawa"},{"type":"compare","title":"Talla Da Biyan Ciki","leftTitle":"Talla","leftItems":["Kyauta","Kudi Daga Talla"],"rightTitle":"Biyan Ciki","rightItems":["Biya","Kudi Kai Tsaye"]},{"type":"hub","title":"Monetization","center":"Kudi","satellites":["Talla","Biya","Sayayya","Premium"]},{"type":"stack","title":"Matakan Kudi","items":["Karba","Hanya","Masu Amfani","App"]}]'
Add-Diag $f 'mob-a1' '[{"type":"flow","title":"Sanarwa","items":["Abu Ya Faru","Server Ya Tura","Waya Ta Nuna","Mai Amfani Ya Bude"],"caption":"Sanarwa tana dawo da masu amfani"},{"type":"compare","title":"Push Da Ciki","leftTitle":"Push","leftItems":["Ko Ba A App","Taimako"],"rightTitle":"Ciki","rightItems":["A Cikin App","Bayani"]},{"type":"hub","title":"Sanarwa","center":"Push","satellites":["Firebase","Server","Waya","User"]},{"type":"stack","title":"Matakan Push","items":["Budewa","Nuna","Turawa","Abin Da Ya Faru"]}]'
Add-Diag $f 'mob-a2' '[{"type":"flow","title":"Tsaron App","items":["Rufe Bayanai","Duba Izini","Sabuntawa","Kare API"],"caption":"App amintacciya amana ce"},{"type":"compare","title":"Amintacce Da Maras Tsaro","leftTitle":"Amintacce","leftItems":["Rufe Bayanai","Izini Kadan"],"rightTitle":"Maras Tsaro","rightItems":["Bude","Izini Da Yawa"]},{"type":"hub","title":"Tsaro","center":"Safe","satellites":["Encrypt","Izini","Update","Auth"]},{"type":"stack","title":"Matakan Tsaro","items":["Auth","Update","Izini","Rufewa"]}]'
Add-Diag $f 'mob-a3' '[{"type":"flow","title":"Sauring App","items":["Auna Sauri","Rage Girman Hoto","Ajiye Cache","Sake Aunawa"],"caption":"App mai sauri ba a sharewa"},{"type":"compare","title":"Sauri Da Jinkiri","leftTitle":"Sauri","leftItems":["Masu Amfani Suna Zama","Taurari Da Yawa"],"rightTitle":"Jinkiri","rightItems":["Ana Sharewa","Taurari Kadan"]},{"type":"hub","title":"Sauri","center":"Speed","satellites":["Hoto","Cache","Code","Memory"]},{"type":"stack","title":"Matakan Sauri","items":["Memory","Code","Cache","Hoto"]}]'
Add-Diag $f 'mob-a4' '[{"type":"flow","title":"CI CD Don Mobile","items":["Tura Code","Test Da Kanta","Build Atomatik","Raba Ga Masu Gwaji"],"caption":"CI CD tana saurin fitar da app"},{"type":"compare","title":"Da Hannu Da Atomatik","leftTitle":"Da Hannu","leftItems":["Jinkiri","Kuskure"],"rightTitle":"Atomatik","rightItems":["Sauri","Daidaito"]},{"type":"hub","title":"CI CD","center":"Build","satellites":["Git","Test","Build","Distribute"]},{"type":"stack","title":"Matakan Build","items":["Raba","Build","Test","Code"]}]'
Add-Diag $f 'mob-a5' '[{"type":"flow","title":"Wearables Da IoT","items":["Naura Ta Tattara","Aika Zuwa App","App Ta Nuna","Mai Amfani Ya Gani"],"caption":"Agogo da naurori suna magana da app"},{"type":"compare","title":"Waya Da Agogo","leftTitle":"Waya","leftItems":["Babba","Mai Iko"],"rightTitle":"Agogo","rightItems":["Karami","Lafiya"]},{"type":"hub","title":"IoT","center":"Naura","satellites":["Agogo","Sensor","App","Cloud"]},{"type":"stack","title":"Matakan IoT","items":["Cloud","App","Sensor","Naura"]}]'
Add-Diag $f 'mob-a6' '[{"type":"flow","title":"Hanya Zuwa Mobile Career","items":["Koyon Flutter","Gina Apps","Buga A Store","Neman Aiki"],"caption":"Apps a store suna magana da kansu"},{"type":"compare","title":"Android Da iOS","leftTitle":"Android","leftItems":["Masu Yawa","Araha"],"rightTitle":"iOS","rightItems":["Kudi","Kadan"]},{"type":"hub","title":"Sanaoin Mobile","center":"Career","satellites":["Android","iOS","Flutter","Freelance"]},{"type":"stack","title":"Matakan Sanaa","items":["Senior","Mid","Junior","Farkon Koyo"]}]'
Write-Output "MOB DONE"
