$ErrorActionPreference = "Stop"
$targetDir = "C:\Users\LAB\Desktop\Hausa Tech\TechHausa\TechHausa\app\src\main\assets\courses"
function Add-Diag {
    param($file, $id, $diag)
    $raw = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8)
    $search = '"id": "' + $id + '"'
    $idPos = $raw.IndexOf($search)
    if ($idPos -lt 0) { Write-Output ("SKIP " + $id); return }
    $quizPos = $raw.IndexOf('"quiz":', $idPos)
    if ($quizPos -lt 0) { Write-Output ("NOQUIZ " + $id); return }
    $raw = $raw.Insert($quizPos, '            "supplementaryDiagrams": ' + $diag + ",`n")
    [System.IO.File]::WriteAllText($file, $raw, [System.Text.Encoding]::UTF8)
    Write-Output ("OK " + $id)
}
$f = "$targetDir\networking.json"
Add-Diag $f 'net-b1' '[{"type":"flow","title":"Yadda Cibiya Ke Aiki","items":["Naura Biyu","Wayar Hadi","Musayar Bayanai","Sadarwa"],"caption":"Network hadin naurori ne"},{"type":"compare","title":"Daya Da Da Yawa","leftTitle":"Daya","leftItems":["Babu Sadarwa","Kebance"],"rightTitle":"Da Yawa","rightItems":["Sadarwa","Raba Abubuwa"]},{"type":"hub","title":"Cibiya","center":"Net","satellites":["Kwamfuta","Waya","Printer","Router"]},{"type":"stack","title":"Matakan Cibiya","items":["App","Naura","Hadi","Wayoyi"]}]'
Add-Diag $f 'net-b2' '[{"type":"flow","title":"Yadda IP Ke Aiki","items":["Kowane Naura Yana Da Lamba","Nemi Yana Da Adireshi","Router Ya Jagoranta","Ya Isa"],"caption":"IP adireshin gida ne na naura"},{"type":"compare","title":"IPv4 Da IPv6","leftTitle":"IPv4","leftItems":["Gajere","Misali 192.168.1.1"],"rightTitle":"IPv6","rightItems":["Tsayi","Na Gaba"]},{"type":"hub","title":"IP","center":"IP","satellites":["IPv4","IPv6","Router","Naura"]},{"type":"stack","title":"Matakan IP","items":["App","IP","Hadi","Wayoyi"]}]'
Add-Diag $f 'net-b3' '[{"type":"flow","title":"Router Switch Modem","items":["Modem Ya Karbo Daga Waje","Router Ya Raba","Switch Ya Hada","Naurori Sun Sadu"],"caption":"Kowane da aikinsa a cibiya"},{"type":"compare","title":"Router Da Switch","leftTitle":"Router","leftItems":["Tsakanin Cibiyoyi","IP"],"rightTitle":"Switch","rightItems":["Cikin Cibiya Daya","MAC"]},{"type":"hub","title":"Naurori","center":"Devices","satellites":["Router","Switch","Modem","Access Point"]},{"type":"stack","title":"Matakan Naurori","items":["Naura","Switch","Router","Modem"]}]'
Add-Diag $f 'net-b4' '[{"type":"flow","title":"WiFi Da Ethernet","items":["Zabi Hanya","Hada Naura","Bada Kalmar Sirri","Fara Amfani"],"caption":"Ethernet waya WiFi iska"},{"type":"compare","title":"WiFi Da Ethernet","leftTitle":"WiFi","leftItems":["Ba Waya","Mai Motsi"],"rightTitle":"Ethernet","rightItems":["Waya","Mafi Sauri"]},{"type":"hub","title":"Hadi","center":"Connect","satellites":["WiFi","Ethernet","Kalmar Sirri","Sauri"]},{"type":"stack","title":"Matakan Hadi","items":["Amfani","Kalmar Sirri","Hadi","Zabi"]}]'
Add-Diag $f 'net-b5' '[{"type":"flow","title":"Yadda Intanet Ke Aiki","items":["Rubuta Adireshi","DNS Ya Fassara","Nemi Ya Tafi Duniya","Shafi Ya Dawo"],"caption":"Intanet cibiyoyi ne da aka hada"},{"type":"compare","title":"Gida Da Duniya","leftTitle":"Gida","leftItems":["Karami","Na Kanka"],"rightTitle":"Duniya","rightItems":["Babba","Kowa"]},{"type":"hub","title":"Intanet","center":"Web","satellites":["ISP","DNS","Server","Browser"]},{"type":"stack","title":"Matakan Intanet","items":["Browser","ISP","DNS","Server"]}]'
Add-Diag $f 'net-b6' '[{"type":"flow","title":"Magance Matsala","items":["Gano Matsala","Duba Wayoyi","Sake Kunna Router","Gwada Sake"],"caption":"Sake kunnawa tana magance da yawa"},{"type":"compare","title":"Sauki Da Wuya","leftTitle":"Sauki","leftItems":["Sake Kunna","Duba Waya"],"rightTitle":"Wuya","rightItems":["Kira ISP","Kwararre"]},{"type":"hub","title":"Matsaloli","center":"Fix","satellites":["Waya","Router","ISP","Sake Kunna"]},{"type":"stack","title":"Matakan Gyara","items":["Kwararre","ISP","Sake Kunna","Dubawa"]}]'
Add-Diag $f 'net-i1' '[{"type":"flow","title":"OSI Guda Bakwai","items":["Daga App Zuwa Waya","Kowane Mataki Yana Rufewa","Aika","Budewa A Daya Bangaren"],"caption":"OSI taswira ce ta sadarwa"},{"type":"compare","title":"Sama Da Kasa","leftTitle":"Sama","leftItems":["App","Mai Amfani"],"rightTitle":"Kasa","rightItems":["Waya","Hardware"]},{"type":"hub","title":"OSI","center":"OSI","satellites":["App","Transport","Network","Physical"]},{"type":"stack","title":"Matakan OSI","items":["App","Transport","Network","Physical"]}]'
Add-Diag $f 'net-i2' '[{"type":"flow","title":"TCP IP","items":["Raba Bayanai","Aika Kashi Kashi","Tabbatar Da Isowa","Hada Su"],"caption":"TCP amintacce IP adireshi"},{"type":"compare","title":"TCP Da UDP","leftTitle":"TCP","leftItems":["Amintacce","Jinkiri"],"rightTitle":"UDP","rightItems":["Sauri","Ba Tabbaci"]},{"type":"hub","title":"Kaidoji","center":"TCP IP","satellites":["TCP","UDP","IP","Port"]},{"type":"stack","title":"Matakan Sadarwa","items":["App","TCP","IP","Waya"]}]'
Add-Diag $f 'net-i3' '[{"type":"flow","title":"Yadda DNS Ke Aiki","items":["Rubuta Suna","Tambayi DNS","DNS Ya Bada Lamba","Nemi Ya Tafi"],"caption":"DNS littafin waya ne na intanet"},{"type":"compare","title":"Suna Da Lamba","leftTitle":"Suna","leftItems":["Saukin Tunawa","google.com"],"rightTitle":"Lamba","rightItems":["Wuya","142.250.1.1"]},{"type":"hub","title":"DNS","center":"DNS","satellites":["Suna","Lamba","Server","Browser"]},{"type":"stack","title":"Matakan DNS","items":["Nemi","Lamba","Fassara","Suna"]}]'
Add-Diag $f 'net-i4' '[{"type":"flow","title":"Bandwidth Da Latency","items":["Auna Sauri","Duba Jinkiri","Kwatanta Bukata","Inganta"],"caption":"Bandwidth fadi Latency jinkiri"},{"type":"compare","title":"Fadi Da Jinkiri","leftTitle":"Fadi","leftItems":["Yawa Lokaci Daya","Bidiyo"],"rightTitle":"Jinkiri","rightItems":["Lokacin Tafiya","Wasa"]},{"type":"hub","title":"Sauri","center":"Speed","satellites":["Mbps","Ping","Bidiyo","Wasa"]},{"type":"stack","title":"Matakan Sauri","items":["App","Bandwidth","Latency","Cibiya"]}]'
Add-Diag $f 'net-i5' '[{"type":"flow","title":"Yadda VPN Ke Aiki","items":["Kunna VPN","Rufin Zirga Zirga","Aika Ta Wata Kasa","Boye Wuri"],"caption":"VPN mayafi ne a intanet"},{"type":"compare","title":"Da VPN Da Ba VPN","leftTitle":"Da VPN","leftItems":["Rufaffe","Boye Wuri"],"rightTitle":"Ba VPN","rightItems":["Bude","A Gani"]},{"type":"hub","title":"VPN","center":"VPN","satellites":["Rufewa","Server","Wuri","Sirri"]},{"type":"stack","title":"Matakan VPN","items":["Nirya","Rufewa","Server","App"]}]'
Add-Diag $f 'net-i6' '[{"type":"flow","title":"Tsaron Cibiya","items":["Canza Kalmar Router","Kunna Firewall","Sabuntawa","Sa Ido"],"caption":"Router bude kofa ce ga gida"},{"type":"compare","title":"Tsohuwa Da Sabuwa","leftTitle":"Tsohuwa","leftItems":["admin admin","Hatsari"],"rightTitle":"Sabuwa","rightItems":["Mai Karfi","Lafiya"]},{"type":"hub","title":"Tsaro","center":"Safe","satellites":["Kalmar Sirri","Firewall","Update","Guest"]},{"type":"stack","title":"Matakan Tsaro","items":["Guest","Update","Firewall","Kalma"]}]'
Add-Diag $f 'net-a1' '[{"type":"flow","title":"Subnetting","items":["Dauki Babbar Cibiya","Raba Kananan","Bada Kowace Sashe","Sarrafa Su"],"caption":"Subnetting rabon gida ne"},{"type":"compare","title":"Babba Da Karami","leftTitle":"Babba","leftItems":["Da Yawa","Wuya A Sarrafa"],"rightTitle":"Karami","rightItems":["Kadan","Sauki"]},{"type":"hub","title":"Subnet","center":"IP","satellites":["Network","Host","Mask","CIDR"]},{"type":"stack","title":"Matakan Subnet","items":["Host","Mask","Network","Babba"]}]'
Add-Diag $f 'net-a2' '[{"type":"flow","title":"Load Balancing","items":["Nemi Ya Zo","Balancer Ya Raba","Servers Sun Amsa","Ba Wani Ya gaji"],"caption":"Balancer mai rarraba kaya ne"},{"type":"compare","title":"Daya Da Da Yawa","leftTitle":"Daya","leftItems":["Zai Iya Faduwa","Iyaka"],"rightTitle":"Da Yawa","rightItems":["Lafiya","Ba Iyaka"]},{"type":"hub","title":"Balancer","center":"LB","satellites":["Server 1","Server 2","Server 3","Monitor"]},{"type":"stack","title":"Matakan LB","items":["User","Balancer","Servers","DB"]}]'
Add-Diag $f 'net-a3' '[{"type":"flow","title":"HTTP 3 Da QUIC","items":["Bude Shafi","Sabuwar Hanya","Sauri Da Tsaro","Ingantaccen Bidiyo"],"caption":"Sabbin kaidoji sauri da tsaro"},{"type":"compare","title":"Tsohuwa Da Sabuwa","leftTitle":"Tsohuwa","leftItems":["HTTP 2","Jinkiri"],"rightTitle":"Sabuwa","rightItems":["HTTP 3","Sauri"]},{"type":"hub","title":"Kaidoji","center":"HTTP","satellites":["HTTP 2","HTTP 3","QUIC","TLS"]},{"type":"stack","title":"Matakan Kaida","items":["App","HTTP","QUIC","Waya"]}]'
Add-Diag $f 'net-a4' '[{"type":"flow","title":"SDN","items":["Raba Iko Da Aiki","Saka Iko A Wuri Daya","Tsara Ta Software","Canjawa Da Sauri"],"caption":"SDN cibiya mai software ke tafiyar"},{"type":"compare","title":"Na Gargajiya Da SDN","leftTitle":"Gargajiya","leftItems":["Kowane Da Kanshi","Jinkiri"],"rightTitle":"SDN","rightItems":["Tsakiya Daya","Sauri"]},{"type":"hub","title":"SDN","center":"Control","satellites":["Controller","Switches","Software","Policy"]},{"type":"stack","title":"Matakan SDN","items":["App","Control","Switches","Waya"]}]'
Add-Diag $f 'net-a5' '[{"type":"flow","title":"5G","items":["Naura Ta Nemi","Tower Ya Amsa","Sauri Mai Yawa","Sabbin Abubuwa"],"caption":"5G hanya ce mai fadi da sauri"},{"type":"compare","title":"4G Da 5G","leftTitle":"4G","leftItems":["Sauri","Yanzu"],"rightTitle":"5G","rightItems":["Mafi Sauri","Gaba"]},{"type":"hub","title":"5G","center":"5G","satellites":["Sauri","Tower","Waya","IoT"]},{"type":"stack","title":"Matakan 5G","items":["App","Waya","Tower","Cibiya"]}]'
Add-Diag $f 'net-a6' '[{"type":"flow","title":"Hanya Zuwa Network Career","items":["Koyon Asali","Gina Lab","Shirya Takarda","Neman Aiki"],"caption":"Lab da takarda suna bude kofa"},{"type":"compare","title":"Admin Da Engineer","leftTitle":"Admin","leftItems":["Kulawa","Yau Da Kullum"],"rightTitle":"Engineer","rightItems":["Tsari","Babban Aiki"]},{"type":"hub","title":"Sanaoin Network","center":"Career","satellites":["Admin","Engineer","Security","Cloud"]},{"type":"stack","title":"Matakan Sanaa","items":["Senior","Mid","Junior","Farkon Koyo"]}]'
Write-Output "NET DONE"
