$ErrorActionPreference = "Stop"
$targetDir = "C:\Users\LAB\Desktop\Hausa Tech\TechHausa\TechHausa\app\src\main\assets\courses"
function Add-Diag {
    param($file, $id, $diag)
    $raw = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8)
    $search = '"id": "' + $id + '"'
    $idPos = $raw.IndexOf($search)
    if ($idPos -lt 0) { Write-Output ("SKIP " + $id); return }
    $quizPos = $raw.IndexOf('"quiz":', $idPos)
    if ($quizPos -lt 0) { Write-Output ("NOQUIZ " + $id); return }
    $raw = $raw.Insert($quizPos, '            "supplementaryDiagrams": ' + $diag + ",`n")
    [System.IO.File]::WriteAllText($file, $raw, [System.Text.Encoding]::UTF8)
    Write-Output ("OK " + $id)
}
$f = "$targetDir\cybersecurity.json"
Add-Diag $f 'cyber-b1' '[{"type":"flow","title":"Yadda Hari Ke Faruwa","items":["Barawu Ya Nemo Wanda Bai Kula Ba","Ya Aika Sako Karya","Wanda Ya Yarda Ya Bude","Bayani Ya Tafi"],"caption":"Tsaro yana farawa da kulawa"},{"type":"compare","title":"Tsaro Da Rashin Tsaro","leftTitle":"Tsaro","leftItems":["Kulawa","Kalmar Sirri Mai Karfi"],"rightTitle":"Rashin Tsaro","rightItems":["Sakaci","Kalmar Sirri Mai Sauki"]},{"type":"hub","title":"Tsaro","center":"Tsaro","satellites":["Kalmar Sirri","Sabuntawa","Kulawa","Ajiye Kwafi"]},{"type":"stack","title":"Matakan Tsaro","items":["Halaye","Kayan Aiki","Sabuntawa","Kalmar Sirri"]}]'
Add-Diag $f 'cyber-b2' '[{"type":"flow","title":"Kirkirar Kalmar Sirri","items":["Tsayi Kalla 12","Hada Haruffa Da Lambobi","Kada A Sake Amfani","Ajiye A Manager"],"caption":"Kalmar sirri mai karfi garkuwa ce"},{"type":"compare","title":"Mai Karfi Da Mai Rauni","leftTitle":"Mai Karfi","leftItems":["Tsayi","Hada Abubuwa"],"rightTitle":"Mai Rauni","rightItems":["Gajere","Suna Da Ranar Haihuwa"]},{"type":"hub","title":"Kalmar Sirri","center":"Password","satellites":["Tsayi","Hadi","Bambanci","Manager"]},{"type":"stack","title":"Matakan Kalma","items":["Manager","Bambanci","Hadi","Tsayi"]}]'
Add-Diag $f 'cyber-b3' '[{"type":"flow","title":"Yadda Phishing Ke Aiki","items":["Sako Karya Ya Zo","Yana Kamar Na Gaskiya","Kana Dannawa","Bayani Ya Tafi"],"caption":"Kada a danna link da gaggawa"},{"type":"compare","title":"Na Gaskiya Da Karya","leftTitle":"Na Gaskiya","leftItems":["Adireshi Daidai","Babu Gaggawa"],"rightTitle":"Karya","rightItems":["Adireshi Mai Ban Mamaki","Gaggawa"]},{"type":"hub","title":"Phishing","center":"Yaadara","satellites":["Imel","Sako","Link","Gaggawa"]},{"type":"stack","title":"Matakan Kariya","items":["Rahoto","Sharewa","Dubawa","Tsayawa"]}]'
Add-Diag $f 'cyber-b4' '[{"type":"flow","title":"Yadda Malware Ke Shiga","items":["Sauke Fayil Mai Hadari","Bude Shi","Cutar Ta Yadu","Bayani Ya Lalace"],"caption":"Antivirus da kulawa suna karewa"},{"type":"compare","title":"Virus Da Ransomware","leftTitle":"Virus","leftItems":["Lalata Fayil","Yaduwa"],"rightTitle":"Ransomware","rightItems":["Rufe Bayanai","Neman Kudi"]},{"type":"hub","title":"Malware","center":"Cutar","satellites":["Virus","Ransomware","Spyware","Trojan"]},{"type":"stack","title":"Matakan Kariya","items":["Antivirus","Sabuntawa","Kulawa","Kwafi"]}]'
Add-Diag $f 'cyber-b5' '[{"type":"flow","title":"Social Engineering","items":["Barawu Ya Bincike Ka","Ya Gina Amana","Ya Nemi Bayani","Ya Amfani Da Shi"],"caption":"Kada a bada bayani ga bako"},{"type":"compare","title":"Amana Da Yaadara","leftTitle":"Amana","leftItems":["Sanannen Mutum","Tabbatacce"],"rightTitle":"Yaadara","rightItems":["Bako","Mara Tabbaci"]},{"type":"hub","title":"Yaadara","center":"Bako","satellites":["Kira","Sako","Kyauta","Gaggawa"]},{"type":"stack","title":"Matakan Kariya","items":["Rahoto","Kin Bayarwa","Tabbatarwa","Tsayawa"]}]'
Add-Diag $f 'cyber-b6' '[{"type":"flow","title":"WiFi Mai Tsaro","items":["Guji WiFi Bude","Yi Amfani Da VPN","Kashe Auto Connect","Manta Da Tsohuwa"],"caption":"WiFi bude hanya ce ga barayi"},{"type":"compare","title":"Bude Da Rufaffe","leftTitle":"Bude","leftItems":["Ba Kalmar Sirri","Kowa Yana Gani"],"rightTitle":"Rufaffe","rightItems":["Kalmar Sirri","Rufaffe"]},{"type":"hub","title":"WiFi","center":"WiFi","satellites":["Kalmar Sirri","VPN","Sabuntawa","Manta"]},{"type":"stack","title":"Matakan WiFi","items":["VPN","Kashe Auto","Kalmar Sirri","Sabuntawa"]}]'
Add-Diag $f 'cyber-i1' '[{"type":"flow","title":"Tsaron Waya","items":["Saka Kulle","Sabunta Tsarin","Sauke Daga Store Kadai","Duba Izini"],"caption":"Waya banki ne da hoto a ciki"},{"type":"compare","title":"Android Da iPhone","leftTitle":"Android","leftItems":["Play Store","Duba Izini"],"rightTitle":"iPhone","rightItems":["App Store","Face ID"]},{"type":"hub","title":"Waya","center":"Mobile","satellites":["Kulle","Sabuntawa","Store","Ajiye Kwafi"]},{"type":"stack","title":"Matakan Waya","items":["Kwafi","Store","Sabuntawa","Kulle"]}]'
Add-Diag $f 'cyber-i2' '[{"type":"flow","title":"Sirri A Sada Zumunta","items":["Duba Saitin Sirri","Rage Bayani","Karbi Abokai Sanannu","Yi Tunani Kafin Wallafa"],"caption":"Abin da ya fita ba ya dawowa"},{"type":"compare","title":"Bude Da Kebantacce","leftTitle":"Bude","leftItems":["Kowa Yana Gani","Hatsari"],"rightTitle":"Kebantacce","rightItems":["Abokai Kadai","Lafiya"]},{"type":"hub","title":"Sada Zumunta","center":"Sirri","satellites":["Facebook","WhatsApp","Instagram","TikTok"]},{"type":"stack","title":"Matakan Sirri","items":["Tunani","Abokai","Rage Bayani","Saiti"]}]'
Add-Diag $f 'cyber-i3' '[{"type":"flow","title":"Zamba Ta Kan Layi","items":["Tayar Da Kyauta","Neman Kudi Gaba","Bacewa Bayan Biya","Wahala"],"caption":"Kyauta mai yawa tambaya ce"},{"type":"compare","title":"Gaskiya Da Zamba","leftTitle":"Gaskiya","leftItems":["Tabbatacce","Babu Gaggawa"],"rightTitle":"Zamba","rightItems":["Mara Tabbaci","Gaggawa Da Kyauta"]},{"type":"hub","title":"Zamba","center":"Scam","satellites":["Kyauta","Gaggawa","Biyan Gaba","Bako"]},{"type":"stack","title":"Matakan Kariya","items":["Rahoto","Bincike","Tsayawa","Tambaya"]}]'
Add-Diag $f 'cyber-i4' '[{"type":"flow","title":"Tsaron Kudi Ta Kan Layi","items":["Yi Amfani Da App Na Banki","Kada A Bada PIN","Duba Sanarwa","Rahoto Da Sauri"],"caption":"PIN sirri ne kada a bada"},{"type":"compare","title":"App Na Banki Da Link","leftTitle":"App","leftItems":["Na Gaskiya","Tsaro"],"rightTitle":"Link","rightItems":["Zai Iya Zama Karya","Hatsari"]},{"type":"hub","title":"Kudin Kan Layi","center":"Kudi","satellites":["App Na Banki","PIN","OTP","Sanarwa"]},{"type":"stack","title":"Matakan Tsaro","items":["Rahoto","Sanarwa","PIN Sirri","App Na Gaskiya"]}]'
Write-Output "CYBER PART1 DONE"
