$ErrorActionPreference = "Stop"
$targetDir = "C:\Users\LAB\Desktop\Hausa Tech\TechHausa\TechHausa\app\src\main\assets\courses"
function Add-Diag {
    param($file, $id, $diag)
    $raw = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8)
    $search = '"id": "' + $id + '"'
    $idPos = $raw.IndexOf($search)
    if ($idPos -lt 0) { Write-Output ("SKIP " + $id); return }
    $quizPos = $raw.IndexOf('"quiz":', $idPos)
    if ($quizPos -lt 0) { Write-Output ("NOQUIZ " + $id); return }
    $raw = $raw.Insert($quizPos, '            "supplementaryDiagrams": ' + $diag + ",`n")
    [System.IO.File]::WriteAllText($file, $raw, [System.Text.Encoding]::UTF8)
    Write-Output ("OK " + $id)
}
$f = "$targetDir\cybersecurity.json"
Add-Diag $f 'cyber-i5' '[{"type":"flow","title":"Yadda 2FA Ke Aiki","items":["Saka Kalmar Sirri","Aika Lamba Zuwa Waya","Saka Lambar","Shiga"],"caption":"2FA kofa biyu ce ga asusu"},{"type":"compare","title":"Kalmar Sirri Kadai Da 2FA","leftTitle":"Kadai","leftItems":["Mataki Daya","Saukin Karya"],"rightTitle":"2FA","rightItems":["Matakai Biyu","Wuya A Karya"]},{"type":"hub","title":"2FA","center":"2FA","satellites":["Kalmar Sirri","SMS","App","Yatsa"]},{"type":"stack","title":"Matakan 2FA","items":["Shiga","Lamba","Kalmar Sirri","Kunna 2FA"]}]'
Add-Diag $f 'cyber-i6' '[{"type":"flow","title":"Halayen Tsaro","items":["Sabunta Kullum","Ajiye Kwafi","Kulawa Da Sako","Koyon Sabuwa"],"caption":"Tsaro halaye ne ba abu daya ba"},{"type":"compare","title":"Mai Kulawa Da Maras Kulawa","leftTitle":"Mai Kulawa","leftItems":["Sabuntawa","Kwafi"],"rightTitle":"Maras Kulawa","rightItems":["Tsohuwa","Babu Kwafi"]},{"type":"hub","title":"Halaye","center":"Habit","satellites":["Sabuntawa","Kwafi","Kulawa","Koyo"]},{"type":"stack","title":"Matakan Halaye","items":["Koyo","Kulawa","Kwafi","Sabuntawa"]}]'
Add-Diag $f 'cyber-a1' '[{"type":"flow","title":"Tsaron Cibiya","items":["Saka Firewall","Raba Cibiya","Sa Ido","Sabunta Dokoki"],"caption":"Cibiya mai tsaro gidan katanga"},{"type":"compare","title":"Firewall Da Antivirus","leftTitle":"Firewall","leftItems":["Kofar Shiga","Tace Zirga Zirga"],"rightTitle":"Antivirus","rightItems":["Cikin Naura","Tace Fayil"]},{"type":"hub","title":"Cibiya","center":"Network","satellites":["Firewall","VPN","Sa Ido","Sabuntawa"]},{"type":"stack","title":"Matakan Cibiya","items":["Sa Ido","Raba Cibiya","Firewall","Kalmar Sirri"]}]'
Add-Diag $f 'cyber-a2' '[{"type":"flow","title":"Yadda Boyewa Ke Aiki","items":["Rubuta Sako","Rufe Da Makulli","Aika Rufaffe","Mai Makulli Ya Bude"],"caption":"Encryption akwatin kulle ne"},{"type":"compare","title":"Rufaffe Da Bude","leftTitle":"Bude","leftItems":["Kowa Yana Karantawa","Hatsari"],"rightTitle":"Rufaffe","rightItems":["Mai Makulli Kadai","Lafiya"]},{"type":"hub","title":"Boye Bayanai","center":"Encrypt","satellites":["HTTPS","WhatsApp","VPN","Kulle"]},{"type":"stack","title":"Matakan Boyewa","items":["Budewa","Aikawa","Rufewa","Sako"]}]'
Add-Diag $f 'cyber-a3' '[{"type":"flow","title":"Tsaron Cloud","items":["Zabi Mai Tsaro","Kunna 2FA","Iyaka Wa Ya Shiga","Ajiye Kwafi"],"caption":"Cloud lafiya idan an sa ido"},{"type":"compare","title":"Gida Da Cloud","leftTitle":"Gida","leftItems":["Kai Kana Kulawa","Iko Mai Yawa"],"rightTitle":"Cloud","rightItems":["Su Suna Kulawa","Raba Alhaki"]},{"type":"hub","title":"Cloud Tsaro","center":"Cloud","satellites":["2FA","Izini","Kwafi","Sa Ido"]},{"type":"stack","title":"Matakan Cloud","items":["Kwafi","Izini","2FA","Zabi"]}]'
Add-Diag $f 'cyber-a4' '[{"type":"flow","title":"Ethical Hacking","items":["Samu Izini","Nemo Rauni","Rubuta Rahoto","Gyara Raunin"],"caption":"Hacker mai kyau yana taimakawa"},{"type":"compare","title":"Mai Kyau Da Mara Kyau","leftTitle":"Mai Kyau","leftItems":["Izini","Taimako"],"rightTitle":"Mara Kyau","rightItems":["Ba Izini","Lalata"]},{"type":"hub","title":"Hacking","center":"Hack","satellites":["Izini","Bincike","Rahoto","Gyara"]},{"type":"stack","title":"Matakan Hack","items":["Gyara","Rahoto","Nemo Rauni","Izini"]}]'
Add-Diag $f 'cyber-a5' '[{"type":"flow","title":"Amsa Ga Hari","items":["Gano Hari","Kulle Kofa","Bincika Lalacewa","Gyara Kuma Koyo"],"caption":"Sauri yana rage lalacewa"},{"type":"compare","title":"Shiri Da Ba Shiri","leftTitle":"Shiri","leftItems":["Tsari Yana Nan","Sauri"],"rightTitle":"Ba Shiri","rightItems":["Rudani","Jinkiri"]},{"type":"hub","title":"Incident","center":"Hari","satellites":["Ganewa","Kullewa","Bincike","Farfadowa"]},{"type":"stack","title":"Matakan Amsa","items":["Koyo","Farfadowa","Kullewa","Ganewa"]}]'
Add-Diag $f 'cyber-a6' '[{"type":"flow","title":"Tsaro Ga Karamin Kasuwanci","items":["Horasa Maikata","Ajiye Kwafi","Kunna 2FA","Shirya Tsari"],"caption":"Karamin kasuwanci ma ana hari"},{"type":"compare","title":"Babba Da Karami","leftTitle":"Babba","leftItems":["Kudi Da Yawa","Kwararru"],"rightTitle":"Karami","rightItems":["Kudi Kadan","Asali Ya Isa"]},{"type":"hub","title":"Kasuwanci","center":"Biz","satellites":["Horawa","Kwafi","2FA","Tsari"]},{"type":"stack","title":"Matakan Kasuwanci","items":["Tsari","2FA","Kwafi","Horawa"]}]'
Write-Output "CYBER PART2 DONE"
