$ErrorActionPreference = "Stop"
$targetDir = "C:\Users\LAB\Desktop\Hausa Tech\TechHausa\TechHausa\app\src\main\assets\courses"
function Add-Diag {
    param($file, $id, $diag)
    $raw = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8)
    $search = '"id": "' + $id + '"'
    $idPos = $raw.IndexOf($search)
    if ($idPos -lt 0) { Write-Output ("SKIP " + $id); return }
    $quizPos = $raw.IndexOf('"quiz":', $idPos)
    if ($quizPos -lt 0) { Write-Output ("NOQUIZ " + $id); return }
    $raw = $raw.Insert($quizPos, '            "supplementaryDiagrams": ' + $diag + ",`n")
    [System.IO.File]::WriteAllText($file, $raw, [System.Text.Encoding]::UTF8)
    Write-Output ("OK " + $id)
}
$f = "$targetDir\programming.json"
Add-Diag $f 'prog-b1' '[{"type":"flow","title":"Yadda Shirye Shirye Ke Aiki","items":["Rubuta Code","Kwamfuta Ta Fassara","Aiwatar Da Umarni","Nuna Sakamako"],"caption":"Programming umarni ne ga kwamfuta"},{"type":"compare","title":"Kwamfuta Da Mutum","leftTitle":"Mutum","leftItems":["Yana Magana Da Harshe","Yana Fahimtar Nufi"],"rightTitle":"Kwamfuta","rightItems":["Tana Da Dokoki","Bata Fahimtar Nufi Sai Umarni"]},{"type":"hub","title":"Shirye Shirye","center":"Code","satellites":["Python","JavaScript","Java","Hausa Tech"]},{"type":"stack","title":"Matakan Program","items":["Aikace Aikace","Yaren Shirye Shirye","Compiler","Hardware"]}]'
Add-Diag $f 'prog-b2' '[{"type":"flow","title":"Amfani Da Masu Canji","items":["Ay yana Canji","Saka Daraja","Yi Amfani Da Ita","Canza Idan Ana So"],"caption":"Masu canji suna rike darajoji"},{"type":"compare","title":"Lamba Da Rubutu","leftTitle":"Lamba","leftItems":["Lissafi","Misali 5 Da 10"],"rightTitle":"Rubutu","rightItems":["Kalmomi","Misali Suna"]},{"type":"hub","title":"Nauukan Bayanai","center":"Data","satellites":["Lamba","Rubutu","Gaskiya Karya","Jerin"]},{"type":"stack","title":"Nauuka","items":["Jerin","Gaskiya Karya","Rubutu","Lamba"]}]'
Add-Diag $f 'prog-b3' '[{"type":"flow","title":"Yadda Sharadi Ke Aiki","items":["Tambaya Idan","Idan Gaskiya Yi Wannan","Idan Karya Yi Wancan","Ci Gaba"],"caption":"If Else yana bada zabin biyu"},{"type":"compare","title":"Idan Da Idan Wani","leftTitle":"Idan Daya","leftItems":["Zabi Biyu","Sauki"],"rightTitle":"Idan Da Yawa","rightItems":["Zabuka Da Yawa","Elif"]},{"type":"hub","title":"Sharadi","center":"If Else","satellites":["Idan","Idan Wani","Idan Ba Haka Ba","Zabi"]},{"type":"stack","title":"Matakan Sharadi","items":["Aiki","Idan Ba Haka Ba","Idan Wani","Idan"]}]'
Add-Diag $f 'prog-b4' '[{"type":"flow","title":"Yadda Madauki Ke Aiki","items":["Fara","Bincika Sharadi","Yi Aiki","Maimaitawa"],"caption":"Loop yana maimaita aiki"},{"type":"compare","title":"For Da While","leftTitle":"For","leftItems":["Adadi Sananne","Misali Sau 5"],"rightTitle":"While","rightItems":["Har Sharadi Ya Cika","Adadi Bai Sananne Ba"]},{"type":"hub","title":"Madaukai","center":"Loop","satellites":["For","While","Break","Continue"]},{"type":"stack","title":"Matakan Loop","items":["Tsayawa","Maimaitawa","Sharadi","Fara"]}]'
Add-Diag $f 'prog-b5' '[{"type":"flow","title":"Yadda Ayyuka Ke Aiki","items":["Ay yana Aiki","Bada Bayani","Yi Lissafi","Mayar Da Amsa"],"caption":"Functions suna sake amfani da code"},{"type":"compare","title":"Da Aiki Da Ba Aiki","leftTitle":"Ba Aiki","leftItems":["Maimaita Code","Wuya A Gyara"],"rightTitle":"Da Aiki","rightItems":["Rubuta Sau Daya","Sake Amfani"]},{"type":"hub","title":"Ayyuka","center":"Function","satellites":["Suna","Bayani","Jiki","Amsa"]},{"type":"stack","title":"Matakan Function","items":["Kira","Jiki","Bayani","Ay yana"]}]'
Add-Diag $f 'prog-b6' '[{"type":"flow","title":"Zaben Yare","items":["Gano Manufa","Duba Yaruka","Gwada Daya","Fara Koyo"],"caption":"Python yare mai kyau na farko"},{"type":"compare","title":"Python Da JavaScript","leftTitle":"Python","leftItems":["Sauki","Data Da AI","Mai Koyarwa"],"rightTitle":"JavaScript","rightItems":["Yanar Gizo","Ko Ina","Aiki Da Yawa"]},{"type":"hub","title":"Yaruka","center":"Yare","satellites":["Python","JavaScript","Java","Dart"]},{"type":"stack","title":"Matakan Zabi","items":["Kwarewa","Alumma","Manufa","Sauki"]}]'
Add-Diag $f 'prog-i1' '[{"type":"flow","title":"Amfani Da Jerin","items":["Kirkiri Jerin","Saka Abubuwa","Samu Abu Daya","Canza Jerin"],"caption":"Arrays suna rike abubuwa da yawa"},{"type":"compare","title":"Jerin Da Masu Canji Daya","leftTitle":"Daya","leftItems":["Daraja Daya","Sauki"],"rightTitle":"Jerin","rightItems":["Darajoji Da Yawa","Index"]},{"type":"hub","title":"Tsarin Bayanai","center":"Data","satellites":["Array","List","Index","Loop"]},{"type":"stack","title":"Matakan Jerin","items":["Bincike","Canji","Samuwa","Kirkire"]}]'
Add-Diag $f 'prog-i2' '[{"type":"flow","title":"Yadda OOP Ke Aiki","items":["Ay yana Class","Kirkiri Object","Object Yana Da Siffofi","Kira Hanyoyi"],"caption":"OOP tana tsara code kamar abubuwa"},{"type":"compare","title":"Class Da Object","leftTitle":"Class","leftItems":["Tsari","Misali Motar Gaba Daya"],"rightTitle":"Object","rightItems":["Ainihi","Misali Motarka"]},{"type":"hub","title":"OOP","center":"OOP","satellites":["Class","Object","Gada","Rufewa"]},{"type":"stack","title":"Matakan OOP","items":["Rufewa","Gada","Object","Class"]}]'
Add-Diag $f 'prog-i3' '[{"type":"flow","title":"Yadda Git Ke Aiki","items":["Canza Code","Ajiye Canji","Tura Zuwa GitHub","Jawo Sabuwa"],"caption":"Git tana kiyaye tarihin code"},{"type":"compare","title":"Da Git Da Ba Git","leftTitle":"Ba Git","leftItems":["Rasa Tarihi","Wuya A Hada Kai"],"rightTitle":"Da Git","rightItems":["Tarihi Yana Nan","Saukin Hada Kai"]},{"type":"hub","title":"Git","center":"Git","satellites":["Commit","Push","Pull","Branch"]},{"type":"stack","title":"Matakan Git","items":["Pull Request","Push","Commit","Canji"]}]'
Add-Diag $f 'prog-i4' '[{"type":"flow","title":"Matakan Debugging","items":["Gano Kuskure","Karanta Sako","Bincika Code","Gyara Kuma Gwada"],"caption":"Debugging yana bukatar hakuri"},{"type":"compare","title":"Kuskuren Rubutu Da Hankali","leftTitle":"Rubutu","leftItems":["Saukin Ganewa","Compiler Yana Fada"],"rightTitle":"Hankali","rightItems":["Wuya","Shiru Shiru"]},{"type":"hub","title":"Debugging","center":"Gyara","satellites":["Print","Debugger","Logs","Gwaji"]},{"type":"stack","title":"Matakan Gyara","items":["Tabbatarwa","Gyara","Bincike","Ganewa"]}]'
Add-Diag $f 'prog-i5' '[{"type":"flow","title":"Yadda API Ke Aiki","items":["App Ta Nemi","API Ta Karba","Server Ya Amsa","App Ta Nuna"],"caption":"API gada ce tsakanin apps"},{"type":"compare","title":"Frontend Da Backend","leftTitle":"Frontend","leftItems":["Abin Da Ake Gani","React Da HTML"],"rightTitle":"Backend","rightItems":["Boye","Server Da Database"]},{"type":"hub","title":"API","center":"API","satellites":["Request","Response","JSON","Endpoint"]},{"type":"stack","title":"Matakan API","items":["Nuna Sakamako","Amsa","Nemi","App"]}]'
Add-Diag $f 'prog-i6' '[{"type":"flow","title":"Yadda Algorithm Ke Aiki","items":["Shigar Da Bayanai","Bi Matakai","Sarrafa","Fitar Da Amsa"],"caption":"Algorithm girke girke ne na lissafi"},{"type":"compare","title":"Sauri Da Jinkiri","leftTitle":"Sauri","leftItems":["Matakai Kadan","Mafi Kyau"],"rightTitle":"Jinkiri","rightItems":["Matakai Da Yawa","Mara Kyau"]},{"type":"hub","title":"Algorithms","center":"Algorithm","satellites":["Rarrabuwa","Bincike","Nawa","Madauki"]},{"type":"stack","title":"Matakan Algorithm","items":["Ingantawa","Gwaji","Tsarawa","Matsala"]}]'
Add-Diag $f 'prog-a1' '[{"type":"flow","title":"Tsarin Bayanai Masu Zurfi","items":["Zabi Tsari","Saka Bayanai","Samu Da Sauri","Inganta"],"caption":"Tsari mai kyau yana saurin aiki"},{"type":"compare","title":"Stack Da Queue","leftTitle":"Stack","leftItems":["Karshe Na Farko","Misali Tari"],"rightTitle":"Queue","rightItems":["Farko Na Farko","Misali Layi"]},{"type":"hub","title":"Data Structures","center":"Tsari","satellites":["Stack","Queue","Tree","HashMap"]},{"type":"stack","title":"Matakan Tsari","items":["Graph","Tree","Jerin","Canji"]}]'
Add-Diag $f 'prog-a2' '[{"type":"flow","title":"Amfani Da Design Pattern","items":["Gano Matsala","Zabi Pattern","Aiwatar","Sake Amfani"],"caption":"Patterns mafita ce da aka gwada"},{"type":"compare","title":"Singleton Da Factory","leftTitle":"Singleton","leftItems":["Kwadai Daya","Duk Duniya"],"rightTitle":"Factory","rightItems":["Kirkirar Abubuwa","Boye Bayani"]},{"type":"hub","title":"Patterns","center":"Pattern","satellites":["Singleton","Factory","Observer","MVC"]},{"type":"stack","title":"Matakan Pattern","items":["Tsari","Aiwatarwa","Zabi","Matsala"]}]'
Add-Diag $f 'prog-a3' '[{"type":"flow","title":"Matakan Testing","items":["Rubuta Test","Gudanar Da Shi","Gano Kuskure","Gyara Kuma Maimaita"],"caption":"Testing tana kama kuskure da wuri"},{"type":"compare","title":"Manual Da Automation","leftTitle":"Manual","leftItems":["Da Hannu","Jinkiri","Kadan"],"rightTitle":"Automation","rightItems":["Da Kanta","Sauri","Da Yawa"]},{"type":"hub","title":"Testing","center":"Test","satellites":["Unit","Integration","E2E","Manual"]},{"type":"stack","title":"Matakan Test","items":["E2E","Integration","Unit","Code"]}]'
Add-Diag $f 'prog-a4' '[{"type":"flow","title":"Yadda Concurrency Ke Aiki","items":["Raba Aiki","Gudanar Tare","Daidaitawa","Hada Sakamako"],"caption":"Concurrency tana gudanar da ayyuka tare"},{"type":"compare","title":"Async Da Sync","leftTitle":"Sync","leftItems":["Jira Daya Bayan Daya","Sauki"],"rightTitle":"Async","rightItems":["Ba Jira","Sauri Amma Rikici"]},{"type":"hub","title":"Concurrency","center":"Tare","satellites":["Thread","Async","Parallel","Lock"]},{"type":"stack","title":"Matakan Tare","items":["Hadawa","Daidaitawa","Raba Aiki","Aiki"]}]'
Add-Diag $f 'prog-a5' '[{"type":"flow","title":"Rubuta Code Mai Tsaro","items":["Duba Bayani","Guji Amana","Rufe Bayanai","Gwada Tsaro"],"caption":"Tsaro yana farawa daga code"},{"type":"compare","title":"Amintacce Da Maras Tsaro","leftTitle":"Amintacce","leftItems":["Duba Bayani","Rufe Sirri"],"rightTitle":"Maras Tsaro","rightItems":["Amana Da Kome","Boye Sirri A Code"]},{"type":"hub","title":"Secure Coding","center":"Tsaro","satellites":["Validation","Encryption","Auth","Updates"]},{"type":"stack","title":"Matakan Tsaro","items":["Sa Ido","Auth","Rufe Bayanai","Duba Bayani"]}]'
Add-Diag $f 'prog-a6' '[{"type":"flow","title":"Hanya Zuwa Software Engineer","items":["Koyon Yare","Gina Projects","Shirya GitHub","Neman Aiki"],"caption":"Projects suna fiye da takarda magana"},{"type":"compare","title":"Frontend Da Backend","leftTitle":"Frontend","leftItems":["Abin Gani","React","Design"],"rightTitle":"Backend","rightItems":["Boye","Server","Database"]},{"type":"hub","title":"Sanaoin Software","center":"Career","satellites":["Frontend","Backend","Full Stack","DevOps"]},{"type":"stack","title":"Matakan Sanaa","items":["Senior","Mid Level","Junior","Farkon Koyo"]}]'
Write-Output "PROG DONE"
