$ErrorActionPreference = "Stop"
$targetDir = "C:\Users\LAB\Desktop\Hausa Tech\TechHausa\TechHausa\app\src\main\assets\courses"
function Add-Diag {
    param($file, $id, $diag)
    $raw = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8)
    $search = '"id": "' + $id + '"'
    $idPos = $raw.IndexOf($search)
    if ($idPos -lt 0) { Write-Output ("SKIP " + $id); return }
    $quizPos = $raw.IndexOf('"quiz":', $idPos)
    if ($quizPos -lt 0) { Write-Output ("NOQUIZ " + $id); return }
    $raw = $raw.Insert($quizPos, '            "supplementaryDiagrams": ' + $diag + ",`n")
    [System.IO.File]::WriteAllText($file, $raw, [System.Text.Encoding]::UTF8)
    Write-Output ("OK " + $id)
}
$f = "$targetDir\web_development.json"
Add-Diag $f 'web-b1' '[{"type":"flow","title":"Yadda Shafi Ke Aiki","items":["Rubuta Adireshi","Browser Ya Nemi","Server Ya Amsa","Shafi Ya Bayyana"],"caption":"Yanar gizo kwamfutoci ne da ke magana"},{"type":"compare","title":"Frontend Da Backend","leftTitle":"Frontend","leftItems":["Abin Da Ake Gani","HTML CSS JS"],"rightTitle":"Backend","rightItems":["Boye A Server","Database"]},{"type":"hub","title":"Yanar Gizo","center":"Web","satellites":["Browser","Server","Domain","Hosting"]},{"type":"stack","title":"Matakan Web","items":["Shafi","Browser","Intanet","Server"]}]'
Add-Diag $f 'web-b2' '[{"type":"flow","title":"Tsarin HTML","items":["Bude Tag","Saka Abun Ciki","Rufe Tag","Maimaitawa"],"caption":"HTML kwarangwal ne na shafi"},{"type":"compare","title":"Heading Da Paragraph","leftTitle":"Heading","leftItems":["Babban Rubutu","h1 Zuwa h6"],"rightTitle":"Paragraph","rightItems":["Bayani","Tag p"]},{"type":"hub","title":"HTML","center":"HTML","satellites":["Headings","Links","Images","Forms"]},{"type":"stack","title":"Tsarin Shafi","items":["Abun Ciki","Jiki","Kai","Takarda"]}]'
Add-Diag $f 'web-b3' '[{"type":"flow","title":"Yadda CSS Ke Aiki","items":["Zabi Abu","Bada Salo","Launi Da Girma","Shafi Ya Yi Kyau"],"caption":"CSS ado ne na shafi"},{"type":"compare","title":"Inline Da External","leftTitle":"Inline","leftItems":["A Cikin Tag","Kadan"],"rightTitle":"External","rightItems":["Fayil Daban","Mai Kyau"]},{"type":"hub","title":"CSS","center":"CSS","satellites":["Launi","Font","Layout","Responsive"]},{"type":"stack","title":"Matakan Salo","items":["Animation","Layout","Launi","HTML"]}]'
Add-Diag $f 'web-b4' '[{"type":"flow","title":"Yadda JavaScript Ke Aiki","items":["Mai Amfani Ya Taba","JS Ya Ji","Ya Canza Shafi","Ba Sake Lodawa"],"caption":"JS tana rayar da shafi"},{"type":"compare","title":"HTML Da JS","leftTitle":"HTML","leftItems":["Tsaye","Ba Motsi"],"rightTitle":"JS","rightItems":["Mai Motsi","Martani"]},{"type":"hub","title":"JavaScript","center":"JS","satellites":["Button","Form","Animation","API Call"]},{"type":"stack","title":"Matakan JS","items":["API","Logic","Events","HTML"]}]'
Add-Diag $f 'web-b5' '[{"type":"flow","title":"Yadda Browser Ke Fassara","items":["Karban HTML","Karban CSS","Gudanar Da JS","Nuna Shafi"],"caption":"Browser mai fassara ne"},{"type":"compare","title":"Chrome Da Firefox","leftTitle":"Chrome","leftItems":["Google","Mafi Amfani"],"rightTitle":"Firefox","rightItems":["Mozilla","Sirri"]},{"type":"hub","title":"Browsers","center":"Browser","satellites":["Chrome","Firefox","Edge","Safari"]},{"type":"stack","title":"Matakan Browser","items":["Nuna Shafi","JS Engine","CSS","HTML Parser"]}]'
Add-Diag $f 'web-b6' '[{"type":"flow","title":"Gina Shafin Farko","items":["Rubuta HTML","Kara CSS","Duba A Browser","Gyara Kuma Maimaita"],"caption":"Fara da sauki kuma gina kadan kadan"},{"type":"compare","title":"Notepad Da VS Code","leftTitle":"Notepad","leftItems":["Sauki","Babu Taimako"],"rightTitle":"VS Code","rightItems":["Taimako","Launuka"]},{"type":"hub","title":"Kayan Aiki","center":"Tools","satellites":["VS Code","Browser","HTML","CSS"]},{"type":"stack","title":"Matakan Gina","items":["Buga","Gwaji","CSS","HTML"]}]'
Add-Diag $f 'web-i1' '[{"type":"flow","title":"Responsive Design","items":["Wayar Hannu","Tablet","Kwamfuta","Duk Suna Daidai"],"caption":"Shafi daya yana aiki ko ina"},{"type":"compare","title":"Fixed Da Responsive","leftTitle":"Fixed","leftItems":["Girma Daya","Ba Ya Canjawa"],"rightTitle":"Responsive","rightItems":["Ya Canjawa","Media Queries"]},{"type":"hub","title":"Responsive","center":"Design","satellites":["Mobile","Tablet","Desktop","Flexbox"]},{"type":"stack","title":"Matakan Responsive","items":["Gwaji","Media Queries","Flexbox","HTML"]}]'
Add-Diag $f 'web-i2' '[{"type":"flow","title":"Yadda React Ke Aiki","items":["Raba Shafi","Kirkiri Components","Hada Su","Sabuntawa Da Kanta"],"caption":"React tana sake amfani da abubuwa"},{"type":"compare","title":"HTML Da React","leftTitle":"HTML","leftItems":["Rubuta Duka","Wuya A Babban Shafi"],"rightTitle":"React","rightItems":["Raba Kananan","Sauki A Babban Shafi"]},{"type":"hub","title":"Frontend","center":"UI","satellites":["React","Vue","Components","State"]},{"type":"stack","title":"Matakan Frontend","items":["App","Components","Framework","JS"]}]'
Add-Diag $f 'web-i3' '[{"type":"flow","title":"Yadda Backend Ke Aiki","items":["Nemi Ya Zo","Server Ya Sarrafa","Database Ta Bada","Amsa Ta Koma"],"caption":"Backend kwakwalwa ce ta shafi"},{"type":"compare","title":"Frontend Da Backend","leftTitle":"Frontend","leftItems":["Gani","Browser"],"rightTitle":"Backend","rightItems":["Hankali","Server"]},{"type":"hub","title":"Backend","center":"Server","satellites":["Node","Python","Database","API"]},{"type":"stack","title":"Matakan Backend","items":["Database","Logic","Server","Nemi"]}]'
Add-Diag $f 'web-i4' '[{"type":"flow","title":"Nauukan Database","items":["Zabi Naui","Tsara Teburi","Ajiye Bayanai","Nemo Lokacin Bukata"],"caption":"Database rumbun bayanai ne"},{"type":"compare","title":"SQL Da NoSQL","leftTitle":"SQL","leftItems":["Teburi","Tsari Mai Kyau"],"rightTitle":"NoSQL","rightItems":["Takardu","Sauki Ya Canjawa"]},{"type":"hub","title":"Databases","center":"DB","satellites":["MySQL","MongoDB","Postgres","Firebase"]},{"type":"stack","title":"Matakan DB","items":["App","Query","Database","Fayil"]}]'
Add-Diag $f 'web-i5' '[{"type":"flow","title":"Yadda REST API Ke Aiki","items":["GET Don Neman","POST Don Aikawa","Server Ya Amsa","App Ta Nuna"],"caption":"REST dokoki ne na sadarwa"},{"type":"compare","title":"GET Da POST","leftTitle":"GET","leftItems":["Neman Bayanai","Ba Canji"],"rightTitle":"POST","rightItems":["Aikawa Bayanai","Canji"]},{"type":"hub","title":"REST","center":"API","satellites":["GET","POST","PUT","DELETE"]},{"type":"stack","title":"Matakan REST","items":["App","JSON","Server","Database"]}]'
Add-Diag $f 'web-i6' '[{"type":"flow","title":"Matakan Hosting","items":["Kammala Shafi","Zabi Mai Hosting","Loda Fayiloli","Shafi Yana Raye"],"caption":"Hosting haya ce ta wuri a intanet"},{"type":"compare","title":"Kyauta Da Biya","leftTitle":"Kyauta","leftItems":["Netlify","Kadan","Na Farko"],"rightTitle":"Biya","rightItems":["Sauri","Da Yawa","Na Kasuwanci"]},{"type":"hub","title":"Hosting","center":"Host","satellites":["Netlify","Vercel","Domain","SSL"]},{"type":"stack","title":"Matakan Buga","items":["Domain","SSL","Fayiloli","Code"]}]'
Add-Diag $f 'web-a1' '[{"type":"flow","title":"Full Stack","items":["Frontend","API","Backend","Database"],"caption":"Full stack duk matakan ne"},{"type":"compare","title":"Frontend Da Full Stack","leftTitle":"Frontend","leftItems":["Gani Kadai","HTML CSS JS"],"rightTitle":"Full Stack","rightItems":["Duka","Frontend Da Backend"]},{"type":"hub","title":"Full Stack","center":"Stack","satellites":["React","API","Node","MongoDB"]},{"type":"stack","title":"Matakan Stack","items":["Database","Backend","API","Frontend"]}]'
Add-Diag $f 'web-a2' '[{"type":"flow","title":"Sauring Shafi","items":["Auna Sauri","Rage Hotuna","Ajiye Cache","Sake Aunawa"],"caption":"Shafi mai sauri yana rike maziyarta"},{"type":"compare","title":"Sauri Da Jinkiri","leftTitle":"Sauri","leftItems":["Maziyarta Suna Zama","Matsayi Mai Kyau"],"rightTitle":"Jinkiri","rightItems":["Maziyarta Suna Tafiya","Matsayi Mara Kyau"]},{"type":"hub","title":"Performance","center":"Sauri","satellites":["Hotuna","Cache","CDN","Code"]},{"type":"stack","title":"Matakan Sauri","items":["CDN","Cache","Rage Girma","Code"]}]'
Add-Diag $f 'web-a3' '[{"type":"flow","title":"Tsaron Shafi","items":["HTTPS","Duba Bayani","Sabuntawa","Ajiye Kwafi"],"caption":"Tsaro amana ce ta maziyarta"},{"type":"compare","title":"HTTP Da HTTPS","leftTitle":"HTTP","leftItems":["Bude","Ba Tsaro"],"rightTitle":"HTTPS","rightItems":["Rufe","Tsaro"]},{"type":"hub","title":"Tsaron Web","center":"Tsaro","satellites":["HTTPS","Validation","Updates","Backup"]},{"type":"stack","title":"Matakan Tsaro","items":["Sa Ido","Backup","Validation","HTTPS"]}]'
Add-Diag $f 'web-a4' '[{"type":"flow","title":"Yadda PWA Ke Aiki","items":["Bude Shafi","Ajiye A Naura","Aiki Ba Intanet","Sanarwa"],"caption":"PWA shafi ne kamar app"},{"type":"compare","title":"PWA Da App","leftTitle":"PWA","leftItems":["Ba Sawa","Shafi"],"rightTitle":"App","rightItems":["Sawa","Store"]},{"type":"hub","title":"PWA","center":"PWA","satellites":["Offline","Install","Push","Sauri"]},{"type":"stack","title":"Matakan PWA","items":["Push","Cache","Manifest","Shafi"]}]'
Add-Diag $f 'web-a5' '[{"type":"flow","title":"SSR Da CSR","items":["Nemi Ya Zo","Shafi Ya Gina","Amsa Ta Koma","Nuna"],"caption":"SSR a server CSR a browser"},{"type":"compare","title":"SSR Da CSR","leftTitle":"SSR","leftItems":["A Server","Sauri Na Farko","SEO Mai Kyau"],"rightTitle":"CSR","rightItems":["A Browser","Jinkiri Na Farko","SEO Mai Wuya"]},{"type":"hub","title":"Rendering","center":"Render","satellites":["SSR","CSR","SEO","Sauri"]},{"type":"stack","title":"Matakan Render","items":["Nuna","JS","Server","Nemi"]}]'
Add-Diag $f 'web-a6' '[{"type":"flow","title":"Hanya Zuwa Web Developer","items":["HTML CSS JS","Gina Projects","Shirya Portfolio","Neman Aiki"],"caption":"Portfolio tana magana da kanta"},{"type":"compare","title":"Frontend Da Backend","leftTitle":"Frontend","leftItems":["Gani","React"],"rightTitle":"Backend","rightItems":["Boye","Node"]},{"type":"hub","title":"Sanaoin Web","center":"Career","satellites":["Frontend","Backend","Full Stack","Freelance"]},{"type":"stack","title":"Matakan Sanaa","items":["Senior","Mid","Junior","Farkon Koyo"]}]'
Write-Output "WEB DONE"
